.TH MAGNOLIE-HANDBUCH 1 "август 2026" "Руководство Magnolie 2.0.16" "Пользовательские команды"
.SH НАЗВАНИЕ
magnolie-handbuch \- открыть руководство пользователя органайзера Magnolie
.SH СИНТАКСИС
.B magnolie-handbuch
.RI [ параметр ]
.RI [ \-\-language\  язык ]
.SH ОПИСАНИЕ
.B Руководство Magnolie
открывает полное иллюстрированное руководство пользователя органайзера
Magnolie. Руководство можно просматривать на экране, печатать или экспортировать
в файл PDF.
.PP
За один пользовательский сеанс открывается только одно окно руководства.
Повторный запуск команды выводит на передний план уже открытое окно.
.SH ФОРМЫ КОМАНДНОЙ СТРОКИ
Нейтральные короткие псевдонимы и английские длинные формы:
.nf
\-h \-\-help; \-V \-\-version; \-l \-\-language; \-P \-\-pot-template.
.fi
Принимаются как немецкие, так и английские длинные формы.
.SH ПАРАМЕТРЫ
.TP
.BR \-\-language " " LANGUAGE , " " \-\-sprache " " SPRACHE
Использовать при этом запуске немецкий (\fBde\fR), английский (\fBen\fR) или
системный язык (\fBsystem\fR). Этот параметр выбирает язык вывода команды до
показа справки и язык WebKit во вновь открытом окне. Сохранённые настройки не
изменяются.
.TP
.BR \-\-pot-template " [" FILE "]", " " \-\-pot " [" ФАЙЛ "]"
Создать воспроизводимый шаблон gettext и завершить работу. Если аргумент файла
не указан, записать \fBmagnolie-handbuch.pot\fR в текущий каталог; иначе
записать по указанному пути. При успешном завершении выводится абсолютный путь
к созданному файлу.
.TP
.BR \-\-help , " " \-\-hilfe
Показать краткий обзор команды.
.SH ОКРУЖЕНИЕ
.TP
.B MAGNOLIE_HANDBUCH_WEB
Использовать другой каталог, содержащий интерфейс руководства. Предназначено
для разработки и тестирования.
.SH "СМ. ТАКЖЕ"
.BR magnolie-organizer (1)
.SH АВТОР
Автор: Майк Вальтер.
