.TH MAGNOLIE-HANDBUCH 1 "жнівень 2026" "Дапаможнік Magnolie 2.0.23" "Каманды карыстальніка"
.SH НАЗВА
magnolie-handbuch \- адкрыць дапаможнік карыстальніка арганайзера Magnolie
.SH СІНОПСІС
.B magnolie-handbuch
.RI [ параметр ]
.RI [ \-\-language\  мова ]
.SH АПІСАННЕ
.B Дапаможнік Magnolie
адкрывае поўны ілюстраваны дапаможнік карыстальніка арганайзера Magnolie.
Дапаможнік можна праглядаць на экране, друкаваць або экспартаваць у файл PDF.
.PP
На працягу аднаго сеанса карыстальніка адкрываецца толькі адно акно
дапаможніка. Паўторны запуск каманды паказвае ўжо адкрытае акно.
.SH ФОРМЫ КАМАНДНАГА РАДКА
Нейтральныя кароткія псеўданімы і англійскія доўгія формы:
.nf
\-h \-\-help; \-V \-\-version; \-l \-\-language; \-P \-\-pot-template.
.fi
Прымаюцца як нямецкія, так і англійскія доўгія формы.
.SH ПАРАМЕТРЫ
.TP
.BR \-\-language " " LANGUAGE , " " \-\-sprache " " SPRACHE
Выкарыстоўваць для гэтага выкліку нямецкую (\fBde\fR), англійскую (\fBen\fR)
або сістэмную мову (\fBsystem\fR). Гэта вызначае мову вываду каманды перад
паказам даведкі і мову WebKit новага акна. Захаваныя налады не змяняюцца.
.TP
.BR \-\-pot-template " [" FILE "]", " " \-\-pot " [" ФАЙЛ "]"
Стварыць узнаўляльны шаблон gettext і завяршыць працу. Калі аргумент файла не
зададзены, запісаць \fBmagnolie-handbuch.pot\fR у бягучы каталог; інакш
запісаць па зададзеным шляху. Пры паспяховым выкананні выводзіцца абсалютны
шлях да выхаднога файла.
.TP
.BR \-\-help , " " \-\-hilfe
Паказаць кароткі агляд каманды.
.SH АСЯРОДДЗЕ
.TP
.B MAGNOLIE_HANDBUCH_WEB
Выкарыстоўваць іншы каталог, які змяшчае інтэрфейс дапаможніка. Прызначана для
распрацоўкі і тэсціравання.
.SH "ГЛ. ТАКСАМА"
.BR magnolie-organizer (1)
.SH АЎТАР
Аўтар: Майк Вальтэр.
