#!/bin/sh
set -eu

tmp="${AUTOPKGTEST_TMP:-$(mktemp -d)}"
mkdir -p "$tmp/home" "$tmp/data" "$tmp/config" "$tmp/state" "$tmp/cache"
unset MAGNOLIE_ORGANIZER_WEB MAGNOLIE_LOCALE_DIR

exec timeout 45s dbus-run-session -- xvfb-run -a \
  -s '-screen 0 1280x800x24' env \
  HOME="$tmp/home" XDG_DATA_HOME="$tmp/data" XDG_CONFIG_HOME="$tmp/config" \
  XDG_STATE_HOME="$tmp/state" XDG_CACHE_HOME="$tmp/cache" \
  GDK_BACKEND=x11 GSETTINGS_BACKEND=memory NO_AT_BRIDGE=1 \
  LIBGL_ALWAYS_SOFTWARE=1 WEBKIT_DISABLE_COMPOSITING_MODE=1 \
  python3 "$(dirname -- "$0")/gtk-webkit.py"
