#!/bin/sh
set -eu

test -x /usr/bin/magnolie-organizer
test -f /usr/share/magnolie-organizer/web/index.html
test -f /usr/share/magnolie-organizer/web/anwendung.js
test -f /usr/share/magnolie-organizer/web/i18n/de.js
test -f /usr/share/magnolie-organizer/klang/erinnerung.wav
test -f /usr/share/locale/de/LC_MESSAGES/magnolie-organizer.mo
test -f /usr/share/doc/magnolie-organizer/ENTWURF-MAGNOLIENBAUM.md.gz
test -f /etc/ufw/applications.d/magnolie-organizer
test -f /usr/share/applications/io.gitlab.maik3531.MagnolieOrganizer.desktop
test ! -e /usr/share/applications/magnolie-organizer.desktop
test -f /usr/share/man/man1/magnolie-organizer.1.gz

dpkg-query -W -f='${Status}\n' magnolie-organizer | grep -qx 'install ok installed'
dpkg -V magnolie-organizer
desktop-file-validate /usr/share/applications/io.gitlab.maik3531.MagnolieOrganizer.desktop
grep -q '^ports=8737/tcp|8737/udp|5353/udp$' \
  /etc/ufw/applications.d/magnolie-organizer

tmp="${AUTOPKGTEST_TMP:-$(mktemp -d)}"
mkdir -p "$tmp/data" "$tmp/config" "$tmp/state"
env -u MAGNOLIE_ORGANIZER_WEB -u MAGNOLIE_LOCALE_DIR \
  XDG_DATA_HOME="$tmp/data" XDG_CONFIG_HOME="$tmp/config" \
  XDG_STATE_HOME="$tmp/state" NO_AT_BRIDGE=1 \
  /usr/bin/magnolie-organizer --language en --help | grep -q 'Usage:'
