pref("general.config.filename", "thunderbird.cfg");
pref("general.config.obscure_value", 0);
pref("general.config.sandbox_enabled", false);
pref("app.update.enabled", false);
pref("app.update.auto", false);
pref("app.update.checkInstallTime", false);
pref("mail.shell.checkDefaultClient", false);
pref("mail.provider.enabled", false);
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("toolkit.telemetry.enabled", false);
pref("toolkit.telemetry.initDelay", 1);
pref("mailnews.start_page.enabled", false);
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.dom.window.dump.enabled", true);
pref("mail.account.account1.server", "server1");
pref("mail.account.account1.identities", "id1");
pref("mail.identity.id1.fullName", "Synthetic Contact Test");
pref("mail.identity.id1.useremail", "contact-oracle@example.invalid");
pref("mail.identity.id1.valid", true);
pref("mail.accountmanager.accounts", "account1");
pref("mail.accountmanager.defaultaccount", "account1");
pref("mail.accountmanager.localfoldersserver", "server1");
pref("mail.server.server1.hostname", "Local Folders");
pref("mail.server.server1.name", "Synthetic Local Folders");
pref("mail.server.server1.type", "none");
pref("mail.server.server1.valid", true);
pref("mail.server.server1.directory-rel", "[ProfD]Mail/Local Folders");
pref("accessibility.force_disabled", 1);
pref("widget.use-xdg-desktop-portal.file-picker", 0);
pref("widget.use-xdg-desktop-portal.mime-handler", 0);
pref("widget.use-xdg-desktop-portal.open-uri", 0);
pref("widget.use-xdg-desktop-portal.settings", 0);
pref("gfx.webrender.software.opengl", true);
pref("mail.inappnotifications.enabled", false);
pref("mail.chat.enabled", false);
