#!/usr/bin/env python3
"""Vereinigt bestehende PO- und generierte Kataloge deterministisch mit einem POT."""

import gettext
import json
import os
import re
import subprocess
import sys
import tempfile

ERGÄNZUNGEN = {
    "Skip deletions": {
        "de": "Löschungen auslassen", "fr": "Ignorer les suppressions", "es": "Omitir eliminaciones", "it": "Ignora le eliminazioni",
        "nl": "Verwijderingen overslaan", "pt": "Ignorar eliminações", "ru": "Не учитывать удаления", "uk": "Пропускати видалення",
        "be": "Прапускаць выдаленні", "cs": "Vynechat mazání", "pl": "Pomijaj usuwanie", "hsb": "Zhašenja wuwostajić",
        "da": "Spring sletninger over", "nb": "Hopp over sletting", "tr": "Silmeleri atla", "hi": "हटाना छोड़ें",
        "ar": "تجاهل الحذف", "ja": "削除を同期しない", "zh_CN": "跳过删除",
    },
    "Notes and tasks synchronize with this paired device. Choose automatic Wi-Fi synchronization or start manually.": {
        "de": "Notizen und Aufgaben werden mit diesem gekoppelten Gerät abgeglichen. Wählen Sie automatischen WLAN-Abgleich oder starten Sie manuell.",
        "fr": "Les notes et tâches sont synchronisées avec cet appareil associé. Choisissez la synchronisation Wi-Fi automatique ou lancez-la manuellement.",
        "es": "Las notas y tareas se sincronizan con este dispositivo emparejado. Elija la sincronización Wi-Fi automática o iníciela manualmente.",
        "it": "Note e attività si sincronizzano con questo dispositivo associato. Scegli la sincronizzazione Wi-Fi automatica o avviala manualmente.",
        "nl": "Notities en taken synchroniseren met dit gekoppelde apparaat. Kies automatische Wi-Fi-synchronisatie of start handmatig.",
        "pt": "Notas e tarefas são sincronizadas com este dispositivo emparelhado. Escolha a sincronização Wi-Fi automática ou inicie manualmente.",
        "ru": "Заметки и задачи синхронизируются с этим сопряжённым устройством. Выберите автоматическую синхронизацию по Wi-Fi или запускайте вручную.",
        "uk": "Нотатки й завдання синхронізуються з цим сполученим пристроєм. Виберіть автоматичну синхронізацію Wi-Fi або запускайте вручну.",
        "be": "Нататкі і задачы сінхранізуюцца з гэтай спалучанай прыладай. Выберыце аўтаматычную сінхранізацыю Wi-Fi або запускайце ўручную.",
        "cs": "Poznámky a úkoly se synchronizují s tímto spárovaným zařízením. Zvolte automatickou synchronizaci Wi-Fi nebo ji spusťte ručně.",
        "pl": "Notatki i zadania synchronizują się z tym sparowanym urządzeniem. Wybierz automatyczną synchronizację Wi-Fi lub uruchamiaj ją ręcznie.",
        "hsb": "Noticy a nadawki so z tutym koplowanym gratom synchronizuja. Wubjerće awtomatisku WLAN-synchronizaciju abo startujće manuelnje.",
        "da": "Noter og opgaver synkroniseres med denne parrede enhed. Vælg automatisk Wi-Fi-synkronisering eller start manuelt.",
        "nb": "Notater og oppgaver synkroniseres med denne parede enheten. Velg automatisk Wi-Fi-synkronisering eller start manuelt.",
        "tr": "Notlar ve görevler bu eşleştirilmiş cihazla eşitlenir. Otomatik Wi-Fi eşitlemesini seçin veya elle başlatın.",
        "hi": "नोट और कार्य इस जोड़े गए डिवाइस से सिंक्रनाइज़ होते हैं। स्वचालित Wi-Fi सिंक्रनाइज़ेशन चुनें या मैन्युअल रूप से शुरू करें।",
        "ar": "تُزامن الملاحظات والمهام مع هذا الجهاز المقترن. اختر المزامنة التلقائية عبر Wi-Fi أو ابدأ يدوياً.",
        "ja": "ノートとタスクをこのペアリング済みデバイスと同期します。自動 Wi-Fi 同期を選ぶか、手動で開始してください。",
        "zh_CN": "笔记和任务会与此已配对设备同步。请选择自动 Wi-Fi 同步或手动启动。",
    },
    "Keep": {
        "de": "Behalten", "fr": "Conserver", "es": "Conservar", "it": "Mantieni", "nl": "Behouden", "pt": "Manter",
        "ru": "Оставить", "cs": "Ponechat", "pl": "Zachowaj", "hsb": "Wobchować", "da": "Behold", "nb": "Behold",
        "hi": "रखें", "zh_CN": "保留", "ja": "保持", "ar": "احتفاظ", "uk": "Зберегти", "be": "Пакінуць", "tr": "Koru",
    },
    "Update both devices to choose the note direction.": {
        "de": "Aktualisieren Sie beide Geräte, um die Notizrichtung auszuwählen.", "fr": "Mettez les deux appareils à jour pour choisir le sens de transfert des notes.",
        "es": "Actualice ambos dispositivos para elegir la dirección de las notas.", "it": "Aggiorna entrambi i dispositivi per scegliere la direzione delle note.",
        "nl": "Werk beide apparaten bij om de richting voor notities te kiezen.", "pt": "Atualize ambos os dispositivos para escolher a direção das notas.",
        "ru": "Обновите оба устройства, чтобы выбрать направление передачи заметок.", "cs": "Aktualizujte obě zařízení, abyste mohli zvolit směr poznámek.",
        "pl": "Zaktualizuj oba urządzenia, aby wybrać kierunek przesyłania notatek.", "hsb": "Aktualizujće wobě grataj, zo byšće směr noticow wubrali.",
        "da": "Opdatér begge enheder for at vælge retningen for noter.", "nb": "Oppdater begge enhetene for å velge retning for notater.",
        "hi": "नोट की दिशा चुनने के लिए दोनों डिवाइस अपडेट करें।", "zh_CN": "请更新两台设备以选择笔记传输方向。",
        "ja": "ノートの転送方向を選ぶには両方のデバイスを更新してください。", "ar": "حدّث الجهازين لاختيار اتجاه نقل الملاحظات.",
        "uk": "Оновіть обидва пристрої, щоб вибрати напрямок передавання нотаток.", "be": "Абнавіце абедзве прылады, каб выбраць напрамак перадачы нататак.",
        "tr": "Not yönünü seçmek için her iki cihazı da güncelleyin.",
    },
    "Note synchronization direction": {
        "de": "Synchronisierungsrichtung für Notizen", "fr": "Sens de synchronisation des notes", "es": "Dirección de sincronización de notas",
        "it": "Direzione di sincronizzazione delle note", "nl": "Synchronisatierichting voor notities", "pt": "Direção de sincronização das notas",
        "ru": "Направление синхронизации заметок", "cs": "Směr synchronizace poznámek", "pl": "Kierunek synchronizacji notatek",
        "hsb": "Směr synchronizacije noticow", "da": "Synkroniseringsretning for noter", "nb": "Synkroniseringsretning for notater",
        "hi": "नोट सिंक्रनाइज़ेशन की दिशा", "zh_CN": "笔记同步方向", "ja": "ノートの同期方向", "ar": "اتجاه مزامنة الملاحظات",
        "uk": "Напрямок синхронізації нотаток", "be": "Напрамак сінхранізацыі нататак", "tr": "Not eşitleme yönü",
    },
    "Two-way synchronization": {
        "de": "In beide Richtungen synchronisieren", "fr": "Synchronisation bidirectionnelle", "es": "Sincronización bidireccional",
        "it": "Sincronizzazione bidirezionale", "nl": "Synchronisatie in beide richtingen", "pt": "Sincronização bidirecional",
        "ru": "Двусторонняя синхронизация", "cs": "Obousměrná synchronizace", "pl": "Synchronizacja dwukierunkowa",
        "hsb": "Synchronizacija we woběmaj směromaj", "da": "Tovejssynkronisering", "nb": "Toveissynkronisering",
        "hi": "दोनों दिशाओं में सिंक्रनाइज़ेशन", "zh_CN": "双向同步", "ja": "双方向同期", "ar": "مزامنة ثنائية الاتجاه",
        "uk": "Двостороння синхронізація", "be": "Двухбаковая сінхранізацыя", "tr": "Çift yönlü eşitleme",
    },
    "Import Notes → Organizer only": {
        "de": "Nur Notes → Organizer importieren", "fr": "Importer uniquement de Notes vers Organizer", "es": "Importar solo de Notes a Organizer",
        "it": "Importa solo da Notes a Organizer", "nl": "Alleen van Notes naar Organizer importeren", "pt": "Importar apenas de Notes para Organizer",
        "ru": "Импорт только из Notes в Organizer", "cs": "Importovat pouze z Notes do Organizeru", "pl": "Importuj tylko z Notes do Organizera",
        "hsb": "Jenož z Notes do Organizera importować", "da": "Importér kun fra Notes til Organizer", "nb": "Importer bare fra Notes til Organizer",
        "hi": "केवल Notes से Organizer में आयात करें", "zh_CN": "仅从 Notes 导入到 Organizer", "ja": "Notes から Organizer へのインポートのみ",
        "ar": "الاستيراد من Notes إلى Organizer فقط", "uk": "Імпорт лише з Notes до Organizer", "be": "Імпартаваць толькі з Notes у Organizer",
        "tr": "Yalnızca Notes → Organizer içe aktarımı",
    },
    "Import mode sends no Organizer notes back and synchronizes no note, notebook or attachment deletions. Tasks remain independent.": {
        "de": "Im Importmodus werden keine Organizer-Notizen zurückgesendet und keine Löschungen von Notizen, Notizbüchern oder Anhängen synchronisiert. Aufgaben bleiben unabhängig.",
        "fr": "Le mode import ne renvoie aucune note d’Organizer et ne synchronise aucune suppression de notes, carnets ou pièces jointes. Les tâches restent indépendantes.",
        "es": "El modo de importación no devuelve notas de Organizer ni sincroniza eliminaciones de notas, cuadernos o adjuntos. Las tareas siguen siendo independientes.",
        "it": "La modalità di importazione non restituisce note di Organizer e non sincronizza eliminazioni di note, taccuini o allegati. Le attività restano indipendenti.",
        "nl": "De importmodus stuurt geen Organizer-notities terug en synchroniseert geen verwijderingen van notities, notitieboeken of bijlagen. Taken blijven onafhankelijk.",
        "pt": "O modo de importação não devolve notas do Organizer nem sincroniza eliminações de notas, cadernos ou anexos. As tarefas permanecem independentes.",
        "ru": "В режиме импорта заметки Organizer не отправляются обратно, а удаления заметок, блокнотов и вложений не синхронизируются. Задачи остаются независимыми.",
        "cs": "Režim importu neposílá poznámky Organizeru zpět a nesynchronizuje mazání poznámek, zápisníků ani příloh. Úkoly zůstávají nezávislé.",
        "pl": "Tryb importu nie odsyła notatek Organizera i nie synchronizuje usuwania notatek, notatników ani załączników. Zadania pozostają niezależne.",
        "hsb": "Importowy modus njepósćele notice Organizera wróćo a njesynchronizuje zhašenja noticow, zapisnikow abo přiwěškow. Nadawki wostanu njewotwisne.",
        "da": "Importtilstand sender ingen Organizer-noter tilbage og synkroniserer ikke sletning af noter, notesbøger eller vedhæftninger. Opgaver forbliver uafhængige.",
        "nb": "Importmodus sender ingen Organizer-notater tilbake og synkroniserer ikke sletting av notater, notatbøker eller vedlegg. Oppgaver forblir uavhengige.",
        "hi": "आयात मोड में Organizer के नोट वापस नहीं भेजे जाते और नोट, नोटबुक या अटैचमेंट हटाने की कार्रवाई सिंक्रनाइज़ नहीं होती। कार्य स्वतंत्र रहते हैं।",
        "zh_CN": "导入模式不会回传 Organizer 笔记，也不会同步笔记、笔记本或附件的删除操作。任务保持独立。",
        "ja": "インポートモードでは Organizer のノートを送り返さず、ノート、ノートブック、添付ファイルの削除も同期しません。タスクは独立したままです。",
        "ar": "لا يعيد وضع الاستيراد إرسال ملاحظات Organizer ولا يزامن حذف الملاحظات أو دفاتر الملاحظات أو المرفقات. تبقى المهام مستقلة.",
        "uk": "У режимі імпорту нотатки Organizer не надсилаються назад, а видалення нотаток, блокнотів і вкладень не синхронізуються. Завдання залишаються незалежними.",
        "be": "У рэжыме імпарту нататкі Organizer не адпраўляюцца назад, а выдаленні нататак, нататнікаў і ўкладанняў не сінхранізуюцца. Задачы застаюцца незалежнымі.",
        "tr": "İçe aktarma modu Organizer notlarını geri göndermez ve not, not defteri veya ek silmelerini eşitlemez. Görevler bağımsız kalır.",
    },
    "The content is unreadable.": {
        "de": "Der Inhalt ist unlesbar.", "fr": "Le contenu est illisible.", "es": "El contenido no se puede leer.",
        "it": "Il contenuto non è leggibile.", "nl": "De inhoud is onleesbaar.", "pt": "O conteúdo é ilegível.",
        "ru": "Содержимое невозможно прочитать.", "cs": "Obsah nelze přečíst.", "pl": "Nie można odczytać zawartości.",
        "hsb": "Wobsah je nječitajomny.", "da": "Indholdet kan ikke læses.", "nb": "Innholdet kan ikke leses.",
        "hi": "सामग्री पढ़ी नहीं जा सकती।", "zh_CN": "内容无法读取。", "ja": "内容を読み取れません。", "ar": "لا يمكن قراءة المحتوى.",
        "uk": "Вміст неможливо прочитати.", "be": "Змесціва немагчыма прачытаць.", "tr": "İçerik okunamıyor.",
    },
    "Import ICS / CSV…": {
        "de": "ICS / CSV importieren …", "fr": "Importer ICS / CSV…", "es": "Importar ICS / CSV…", "it": "Importa ICS / CSV…",
        "nl": "ICS / CSV importeren…", "pt": "Importar ICS / CSV…", "ru": "Импортировать ICS / CSV…", "cs": "Importovat ICS / CSV…",
        "pl": "Importuj ICS / CSV…", "hsb": "ICS / CSV importować …", "da": "Importér ICS / CSV…", "nb": "Importer ICS / CSV…",
        "hi": "ICS / CSV आयात करें…", "zh_CN": "导入 ICS / CSV…", "ja": "ICS / CSV をインポート…", "ar": "استيراد ICS / CSV…",
        "uk": "Імпортувати ICS / CSV…", "be": "Імпартаваць ICS / CSV…", "tr": "ICS / CSV içe aktar…",
    },
    "The import exceeds the supported limits.": {
        "de": "Der Import überschreitet die unterstützten Grenzen.", "fr": "L’importation dépasse les limites prises en charge.",
        "es": "La importación supera los límites admitidos.", "it": "L’importazione supera i limiti supportati.",
        "nl": "De import overschrijdt de ondersteunde limieten.", "pt": "A importação excede os limites suportados.",
        "ru": "Импорт превышает поддерживаемые ограничения.", "cs": "Import překračuje podporované limity.",
        "pl": "Import przekracza obsługiwane limity.", "hsb": "Import překročuje podpěrane mjezy.",
        "da": "Importen overskrider de understøttede grænser.", "nb": "Importen overskrider de støttede grensene.",
        "hi": "आयात समर्थित सीमाओं से अधिक है।", "zh_CN": "导入内容超出支持的限制。", "ja": "インポート内容が対応する上限を超えています。",
        "ar": "يتجاوز الاستيراد الحدود المدعومة.", "uk": "Імпорт перевищує підтримувані обмеження.",
        "be": "Імпарт перавышае падтрымліваныя абмежаванні.", "tr": "İçe aktarma desteklenen sınırları aşıyor.",
    },
    "First row contains headings": {
        "de": "Erste Zeile enthält Überschriften", "fr": "La première ligne contient les en-têtes", "es": "La primera fila contiene encabezados",
        "it": "La prima riga contiene le intestazioni", "nl": "Eerste rij bevat kolomkoppen", "pt": "A primeira linha contém cabeçalhos",
        "ru": "Первая строка содержит заголовки", "cs": "První řádek obsahuje záhlaví", "pl": "Pierwszy wiersz zawiera nagłówki",
        "hsb": "Prěnja linka napisma wobsahuje", "da": "Første række indeholder overskrifter", "nb": "Første rad inneholder overskrifter",
        "hi": "पहली पंक्ति में शीर्षक हैं", "zh_CN": "首行为列标题", "ja": "先頭行を見出しとして使用", "ar": "يحتوي الصف الأول على عناوين",
        "uk": "Перший рядок містить заголовки", "be": "Першы радок змяшчае загалоўкі", "tr": "İlk satır başlıkları içerir",
    },
    "Date format": {
        "de": "Datumsformat", "fr": "Format de date", "es": "Formato de fecha", "it": "Formato della data", "nl": "Datumnotatie",
        "pt": "Formato da data", "ru": "Формат даты", "cs": "Formát data", "pl": "Format daty", "hsb": "Datumowy format",
        "da": "Datoformat", "nb": "Datoformat", "hi": "तारीख़ का प्रारूप", "zh_CN": "日期格式", "ja": "日付形式", "ar": "تنسيق التاريخ",
        "uk": "Формат дати", "be": "Фармат даты", "tr": "Tarih biçimi",
    },
    "Waste type": {
        "de": "Müllart", "fr": "Type de déchets", "es": "Tipo de residuo", "it": "Tipo di rifiuto", "nl": "Afvalsoort",
        "pt": "Tipo de resíduo", "ru": "Вид отходов", "cs": "Druh odpadu", "pl": "Rodzaj odpadów", "hsb": "Družina wotpadkow",
        "da": "Affaldstype", "nb": "Avfallstype", "hi": "कचरे का प्रकार", "zh_CN": "垃圾类型", "ja": "ごみの種類", "ar": "نوع النفايات",
        "uk": "Вид відходів", "be": "Від адходаў", "tr": "Atık türü",
    },
    "Loading…": {
        "de": "Wird geladen …", "fr": "Chargement…", "es": "Cargando…", "it": "Caricamento…", "nl": "Laden…", "pt": "A carregar…",
        "ru": "Загрузка…", "cs": "Načítání…", "pl": "Wczytywanie…", "hsb": "Začituje so…", "da": "Indlæser…", "nb": "Laster…",
        "hi": "लोड हो रहा है…", "zh_CN": "正在加载…", "ja": "読み込み中…", "ar": "جارٍ التحميل…", "uk": "Завантаження…", "be": "Загрузка…", "tr": "Yükleniyor…",
    },
    "Remove": {
        "de": "Entfernen", "fr": "Retirer", "es": "Quitar", "it": "Rimuovi", "nl": "Verwijderen", "pt": "Remover",
        "ru": "Убрать", "cs": "Odebrat", "pl": "Usuń", "hsb": "Wotstronić", "da": "Fjern", "nb": "Fjern",
        "hi": "हटाएँ", "zh_CN": "移除", "ja": "削除", "ar": "إزالة", "uk": "Прибрати", "be": "Прыбраць", "tr": "Kaldır",
    },
    "Advanced": {
        "de": "Erweitert", "fr": "Avancé", "es": "Avanzado", "it": "Avanzate", "nl": "Geavanceerd", "pt": "Avançado",
        "ru": "Дополнительно", "cs": "Pokročilé", "pl": "Zaawansowane", "hsb": "Rozšěrjene", "da": "Avanceret", "nb": "Avansert",
        "hi": "उन्नत", "zh_CN": "高级", "ja": "詳細設定", "ar": "متقدم", "uk": "Додатково", "be": "Дадаткова", "tr": "Gelişmiş",
    },
    "Link existing contact": {
        "de": "Vorhandene Karteikarte verknüpfen", "fr": "Lier un contact existant", "es": "Vincular un contacto existente",
        "it": "Collega un contatto esistente", "nl": "Bestaand contact koppelen", "pt": "Associar contacto existente",
        "ru": "Связать существующий контакт", "cs": "Propojit stávající kontakt", "pl": "Połącz istniejący kontakt",
        "hsb": "Eksistowacy kontakt zwjazać", "da": "Tilknyt eksisterende kontakt", "nb": "Koble til eksisterende kontakt",
        "hi": "मौजूदा संपर्क जोड़ें", "zh_CN": "关联现有联系人", "ja": "既存の連絡先を関連付ける", "ar": "ربط جهة اتصال حالية",
        "uk": "Пов’язати наявний контакт", "be": "Звязаць існуючы кантакт", "tr": "Mevcut kişiyi bağla",
    },
    "Choose an address": {
        "de": "Anschrift auswählen", "fr": "Choisir une adresse", "es": "Elegir una dirección", "it": "Scegli un indirizzo",
        "nl": "Adres kiezen", "pt": "Escolher uma morada", "ru": "Выбрать адрес", "cs": "Vybrat adresu", "pl": "Wybierz adres",
        "hsb": "Adresu wubrać", "da": "Vælg en adresse", "nb": "Velg en adresse", "hi": "पता चुनें", "zh_CN": "选择地址",
        "ja": "住所を選択", "ar": "اختيار عنوان", "uk": "Вибрати адресу", "be": "Выбраць адрас", "tr": "Adres seç",
    },
    "Email address": {
        "de": "E-Mail-Adresse", "fr": "Adresse e-mail", "es": "Dirección de correo electrónico", "it": "Indirizzo email",
        "nl": "E-mailadres", "pt": "Endereço de e-mail", "ru": "Адрес электронной почты", "cs": "E-mailová adresa",
        "pl": "Adres e-mail", "hsb": "E-mejlowa adresa", "da": "E-mailadresse", "nb": "E-postadresse", "hi": "ईमेल पता",
        "zh_CN": "电子邮箱地址", "ja": "メールアドレス", "ar": "عنوان البريد الإلكتروني", "uk": "Адреса електронної пошти",
        "be": "Адрас электроннай пошты", "tr": "E-posta adresi",
    },
    "Region": {
        "de": "Region", "fr": "Région", "es": "Región", "it": "Regione", "nl": "Regio", "pt": "Região",
        "ru": "Регион", "cs": "Region", "pl": "Region", "hsb": "Region", "da": "Region", "nb": "Region",
        "hi": "क्षेत्र", "zh_CN": "地区", "ja": "地域", "ar": "المنطقة", "uk": "Регіон", "be": "Рэгіён", "tr": "Bölge",
    },
    "PO box": {
        "de": "Postfach", "fr": "Boîte postale", "es": "Apartado postal", "it": "Casella postale", "nl": "Postbus",
        "pt": "Apartado", "ru": "Абонентский ящик", "cs": "Poštovní přihrádka", "pl": "Skrytka pocztowa", "hsb": "Póštowy fach",
        "da": "Postboks", "nb": "Postboks", "hi": "डाक पेटी", "zh_CN": "邮政信箱", "ja": "私書箱", "ar": "صندوق بريد",
        "uk": "Абонентська скринька", "be": "Абаненцкая скрыня", "tr": "Posta kutusu",
    },
    "Address supplement": {
        "de": "Adresszusatz", "fr": "Complément d’adresse", "es": "Complemento de dirección", "it": "Complemento di indirizzo",
        "nl": "Adrestoevoeging", "pt": "Complemento da morada", "ru": "Дополнение к адресу", "cs": "Doplněk adresy",
        "pl": "Uzupełnienie adresu", "hsb": "Adresowy dodawk", "da": "Adressetilføjelse", "nb": "Adressetillegg",
        "hi": "पते का अतिरिक्त विवरण", "zh_CN": "地址补充信息", "ja": "住所の補足", "ar": "تفاصيل إضافية للعنوان",
        "uk": "Доповнення до адреси", "be": "Дапаўненне да адраса", "tr": "Ek adres bilgisi",
    },
    "Birth name: %(name)s": {
        "de": "Geburtsname: %(name)s", "fr": "Nom de naissance : %(name)s", "es": "Apellido de nacimiento: %(name)s",
        "it": "Cognome alla nascita: %(name)s", "nl": "Geboortenaam: %(name)s", "pt": "Apelido de nascimento: %(name)s",
        "ru": "Фамилия при рождении: %(name)s", "cs": "Rodné příjmení: %(name)s", "pl": "Nazwisko rodowe: %(name)s",
        "hsb": "Rodźene mjeno: %(name)s", "da": "Fødenavn: %(name)s", "nb": "Fødenavn: %(name)s",
        "hi": "जन्म का उपनाम: %(name)s", "zh_CN": "出生姓氏：%(name)s", "ja": "出生時の姓：%(name)s",
        "ar": "اسم العائلة عند الولادة: %(name)s", "uk": "Прізвище при народженні: %(name)s",
        "be": "Прозвішча пры нараджэнні: %(name)s", "tr": "Doğumdaki soyadı: %(name)s",
    },
    "The entry could not be found.": {
        "de": "Der Eintrag wurde nicht gefunden.", "fr": "L’entrée est introuvable.",
        "es": "No se ha encontrado la entrada.", "it": "Impossibile trovare la voce.",
        "nl": "De vermelding is niet gevonden.", "pt": "Não foi possível encontrar a entrada.",
        "ru": "Запись не найдена.", "cs": "Položka nebyla nalezena.", "pl": "Nie znaleziono wpisu.",
        "hsb": "Zapisk njebu namakany.", "da": "Posten blev ikke fundet.", "nb": "Oppføringen ble ikke funnet.",
        "hi": "प्रविष्टि नहीं मिली।", "zh_CN": "找不到该条目。", "ja": "項目が見つかりませんでした。",
        "ar": "تعذر العثور على الإدخال.", "uk": "Запис не знайдено.", "be": "Запіс не знойдзены.",
        "tr": "Kayıt bulunamadı.",
    },
    "The remote contact was deleted. Keep this contact and restore it on the next synchronization?": {
        "de": "Der Kontakt wurde auf der Gegenseite gelöscht. Diesen Kontakt behalten und beim nächsten Abgleich dort wiederherstellen?",
        "fr": "Le contact distant a été supprimé. Conserver ce contact et le restaurer lors de la prochaine synchronisation ?",
        "es": "Se ha eliminado el contacto remoto. ¿Conservar este contacto y restaurarlo en la próxima sincronización?",
        "it": "Il contatto remoto è stato eliminato. Conservare questo contatto e ripristinarlo alla prossima sincronizzazione?",
        "nl": "Het externe contact is verwijderd. Dit contact behouden en bij de volgende synchronisatie herstellen?",
        "pt": "O contacto remoto foi eliminado. Manter este contacto e restaurá-lo na próxima sincronização?",
        "ru": "Удалённый контакт был удалён. Сохранить этот контакт и восстановить его при следующей синхронизации?",
        "cs": "Vzdálený kontakt byl odstraněn. Ponechat tento kontakt a obnovit jej při příští synchronizaci?",
        "pl": "Kontakt zdalny został usunięty. Zachować ten kontakt i odtworzyć go podczas następnej synchronizacji?",
        "hsb": "Zdaleny kontakt bu zhašeny. Tutón kontakt wobchować a při přichodnej synchronizaciji wobnowić?",
        "da": "Den eksterne kontakt blev slettet. Behold denne kontakt, og gendan den ved næste synkronisering?",
        "nb": "Den eksterne kontakten ble slettet. Beholde denne kontakten og gjenopprette den ved neste synkronisering?",
        "hi": "दूरस्थ संपर्क हटा दिया गया है। इस संपर्क को रखें और अगले समन्वयन पर उसे पुनर्स्थापित करें?",
        "zh_CN": "远程联系人已被删除。是否保留此联系人，并在下次同步时恢复？",
        "ja": "リモートの連絡先が削除されました。この連絡先を保持し、次回の同期時に復元しますか？",
        "ar": "حُذفت جهة الاتصال البعيدة. هل تريد الاحتفاظ بجهة الاتصال هذه واستعادتها عند المزامنة التالية؟",
        "uk": "Віддалений контакт видалено. Зберегти цей контакт і відновити його під час наступної синхронізації?",
        "be": "Аддалены кантакт выдалены. Захаваць гэты кантакт і аднавіць яго падчас наступнай сінхранізацыі?",
        "tr": "Uzak kişi silindi. Bu kişi korunsun ve sonraki eşitlemede geri yüklensin mi?",
    },
    "Use newer version": {
        "de": "Neuere Fassung verwenden", "fr": "Utiliser la version la plus récente", "es": "Usar la versión más reciente",
        "it": "Usa la versione più recente", "nl": "Nieuwere versie gebruiken", "pt": "Usar a versão mais recente",
        "ru": "Использовать более новую версию", "cs": "Použít novější verzi", "pl": "Użyj nowszej wersji",
        "hsb": "Nowšu wersiju wužiwać", "da": "Brug nyere version", "nb": "Bruk nyere versjon",
        "hi": "नया संस्करण उपयोग करें", "zh_CN": "使用较新版本", "ja": "新しい版を使用", "ar": "استخدام النسخة الأحدث",
        "uk": "Використати новішу версію", "be": "Выкарыстаць навейшую версію", "tr": "Daha yeni sürümü kullan",
    },
    "Reliable modification times are not available for both versions.": {
        "de": "Es liegen nicht für beide Fassungen verlässliche Änderungszeiten vor.",
        "fr": "Les dates de modification fiables ne sont pas disponibles pour les deux versions.",
        "es": "No hay fechas de modificación fiables para ambas versiones.",
        "it": "Non sono disponibili date di modifica affidabili per entrambe le versioni.",
        "nl": "Er zijn niet voor beide versies betrouwbare wijzigingstijden beschikbaar.",
        "pt": "Não estão disponíveis datas de alteração fiáveis para ambas as versões.",
        "ru": "Достоверное время изменения доступно не для обеих версий.",
        "cs": "Pro obě verze nejsou k dispozici spolehlivé časy změn.",
        "pl": "Wiarygodne daty modyfikacji nie są dostępne dla obu wersji.",
        "hsb": "Za wobě wersiji njejsu spušćomne časy změnow k dispoziciji.",
        "da": "Der findes ikke pålidelige ændringstidspunkter for begge versioner.",
        "nb": "Pålitelige endringstidspunkter er ikke tilgjengelige for begge versjonene.",
        "hi": "दोनों संस्करणों के लिए विश्वसनीय संशोधन समय उपलब्ध नहीं हैं।",
        "zh_CN": "并非两个版本都有可靠的修改时间。", "ja": "両方の版について信頼できる更新日時が揃っていません。",
        "ar": "لا تتوفر أوقات تعديل موثوقة لكلا النسختين.",
        "uk": "Достовірний час зміни доступний не для обох версій.",
        "be": "Дакладны час змены даступны не для абедзвюх версій.",
        "tr": "Her iki sürüm için güvenilir değişiklik zamanları mevcut değil.",
    },
    "Prefer newer contact versions when reliable modification times are available.": {
        "de": "Neuere Kontaktfassungen bevorzugen, wenn verlässliche Änderungszeiten vorliegen.",
        "fr": "Privilégier les versions les plus récentes des contacts lorsque les dates de modification sont fiables.",
        "es": "Preferir las versiones más recientes de los contactos cuando haya fechas de modificación fiables.",
        "it": "Preferisci le versioni più recenti dei contatti quando sono disponibili date di modifica affidabili.",
        "nl": "Geef nieuwere contactversies de voorkeur als betrouwbare wijzigingstijden beschikbaar zijn.",
        "pt": "Preferir as versões mais recentes dos contactos quando existirem datas de alteração fiáveis.",
        "ru": "Предпочитать более новые версии контактов при наличии достоверного времени изменения.",
        "cs": "Upřednostňovat novější verze kontaktů, pokud jsou k dispozici spolehlivé časy změn.",
        "pl": "Preferuj nowsze wersje kontaktów, gdy dostępne są wiarygodne daty modyfikacji.",
        "hsb": "Nowše wersije kontaktow preferować, jeli su spušćomne časy změnow k dispoziciji.",
        "da": "Foretræk nyere kontaktversioner, når pålidelige ændringstidspunkter er tilgængelige.",
        "nb": "Foretrekk nyere kontaktversjoner når pålitelige endringstidspunkter er tilgjengelige.",
        "hi": "विश्वसनीय संशोधन समय उपलब्ध होने पर संपर्कों के नए संस्करणों को प्राथमिकता दें।",
        "zh_CN": "有可靠的修改时间时，优先使用较新的联系人版本。",
        "ja": "信頼できる更新日時がある場合は、新しい連絡先の版を優先する。",
        "ar": "تفضيل النسخ الأحدث لجهات الاتصال عند توفر أوقات تعديل موثوقة.",
        "uk": "Надавати перевагу новішим версіям контактів за наявності достовірного часу зміни.",
        "be": "Аддаваць перавагу навейшым версіям кантактаў пры наяўнасці дакладнага часу змены.",
        "tr": "Güvenilir değişiklik zamanları mevcut olduğunda daha yeni kişi sürümlerini tercih et.",
    },
    "Choose contact photo": {
        "de": "Kontaktfoto auswählen", "fr": "Choisir la photo du contact", "es": "Elegir foto del contacto", "it": "Scegli la foto del contatto",
        "nl": "Contactfoto kiezen", "pt": "Escolher fotografia do contacto", "ru": "Выбрать фото контакта", "cs": "Vybrat fotografii kontaktu",
        "pl": "Wybierz zdjęcie kontaktu", "hsb": "Kontaktowe foto wubrać", "da": "Vælg kontaktbillede", "nb": "Velg kontaktbilde",
        "hi": "संपर्क फ़ोटो चुनें", "zh_CN": "选择联系人照片", "ja": "連絡先の写真を選択", "ar": "اختيار صورة جهة الاتصال",
        "uk": "Вибрати фото контакту", "be": "Выбраць фота кантакту", "tr": "Kişi fotoğrafı seç",
    },
    "Choose local image…": {
        "de": "Eigenes Bild wählen…", "fr": "Choisir une image locale…", "es": "Elegir imagen local…", "it": "Scegli immagine locale…",
        "nl": "Lokale afbeelding kiezen…", "pt": "Escolher imagem local…", "ru": "Выбрать локальное изображение…", "cs": "Vybrat místní obrázek…",
        "pl": "Wybierz obraz lokalny…", "hsb": "Swójski wobraz wubrać…", "da": "Vælg lokalt billede…", "nb": "Velg lokalt bilde…",
        "hi": "स्थानीय चित्र चुनें…", "zh_CN": "选择本地图片…", "ja": "ローカル画像を選択…", "ar": "اختيار صورة محلية…",
        "uk": "Вибрати локальне зображення…", "be": "Выбраць лакальную выяву…", "tr": "Yerel resim seç…",
    },
    "Local image": {
        "de": "Eigenes Bild", "fr": "Image locale", "es": "Imagen local", "it": "Immagine locale", "nl": "Lokale afbeelding", "pt": "Imagem local",
        "ru": "Локальное изображение", "cs": "Místní obrázek", "pl": "Obraz lokalny", "hsb": "Swójski wobraz", "da": "Lokalt billede", "nb": "Lokalt bilde",
        "hi": "स्थानीय चित्र", "zh_CN": "本地图片", "ja": "ローカル画像", "ar": "صورة محلية", "uk": "Локальне зображення", "be": "Лакальная выява", "tr": "Yerel resim",
    },
    "Create a drawing sheet in the custom tab first.": {
        "de": "Legen Sie zuerst ein Zeichenblatt in der benutzerdefinierten Registerkarte an.",
        "fr": "Créez d’abord une feuille de dessin dans l’onglet personnalisé.",
        "es": "Cree primero una hoja de dibujo en la pestaña personalizada.",
        "it": "Crea prima un foglio da disegno nella scheda personalizzata.",
        "nl": "Maak eerst een tekenblad op het aangepaste tabblad.",
        "pt": "Crie primeiro uma folha de desenho no separador personalizado.",
        "ru": "Сначала создайте лист для рисования на пользовательской вкладке.",
        "cs": "Nejprve vytvořte kreslicí list na vlastní kartě.",
        "pl": "Najpierw utwórz arkusz rysunku na karcie niestandardowej.",
        "hsb": "Załožće najprjedy rysowanske łopjeno w swójskej rajtarkowej karće.",
        "da": "Opret først et tegneark på den brugerdefinerede fane.",
        "nb": "Opprett først et tegneark i den egendefinerte fanen.",
        "hi": "पहले कस्टम टैब में एक चित्रांकन पृष्ठ बनाएँ।",
        "zh_CN": "请先在自定义标签页中创建绘图页。",
        "ja": "まずカスタムタブで描画シートを作成してください。",
        "ar": "أنشئ أولًا ورقة رسم في علامة التبويب المخصصة.",
        "uk": "Спочатку створіть аркуш для малювання на власній вкладці.",
        "be": "Спачатку стварыце аркуш для малявання на ўласнай укладцы.",
        "tr": "Önce özel sekmede bir çizim sayfası oluşturun.",
    },
    "Drawing sheet": {
        "de": "Zeichenblatt", "fr": "Feuille de dessin", "es": "Hoja de dibujo", "it": "Foglio da disegno", "nl": "Tekenblad", "pt": "Folha de desenho",
        "ru": "Лист для рисования", "cs": "Kreslicí list", "pl": "Arkusz rysunku", "hsb": "Rysowanske łopjeno", "da": "Tegneark", "nb": "Tegneark",
        "hi": "चित्रांकन पृष्ठ", "zh_CN": "绘图页", "ja": "描画シート", "ar": "ورقة رسم", "uk": "Аркуш для малювання", "be": "Аркуш для малявання", "tr": "Çizim sayfası",
    },
    "Eraser": {
        "de": "Radierer", "fr": "Gomme", "es": "Borrador", "it": "Gomma", "nl": "Gum", "pt": "Borracha", "ru": "Ластик", "cs": "Guma", "pl": "Gumka",
        "hsb": "Guma", "da": "Viskelæder", "nb": "Viskelær", "hi": "रबड़", "zh_CN": "橡皮擦", "ja": "消しゴム", "ar": "ممحاة", "uk": "Гумка", "be": "Гумка", "tr": "Silgi",
    },
    "Drawing tool": {
        "de": "Zeichenwerkzeug", "fr": "Outil de dessin", "es": "Herramienta de dibujo", "it": "Strumento di disegno", "nl": "Tekengereedschap", "pt": "Ferramenta de desenho",
        "ru": "Инструмент рисования", "cs": "Kreslicí nástroj", "pl": "Narzędzie rysowania", "hsb": "Rysowanski nastroj", "da": "Tegneværktøj", "nb": "Tegneverktøy",
        "hi": "चित्रांकन उपकरण", "zh_CN": "绘图工具", "ja": "描画ツール", "ar": "أداة الرسم", "uk": "Інструмент малювання", "be": "Інструмент малявання", "tr": "Çizim aracı",
    },
    "Line width": {
        "de": "Strichbreite", "fr": "Épaisseur du trait", "es": "Grosor del trazo", "it": "Spessore del tratto", "nl": "Lijndikte", "pt": "Espessura do traço",
        "ru": "Толщина линии", "cs": "Tloušťka čáry", "pl": "Grubość linii", "hsb": "Šěrokosć linije", "da": "Stregtykkelse", "nb": "Strektykkelse",
        "hi": "रेखा की चौड़ाई", "zh_CN": "线条宽度", "ja": "線の太さ", "ar": "سمك الخط", "uk": "Товщина лінії", "be": "Таўшчыня лініі", "tr": "Çizgi kalınlığı",
    },
    "Export PNG": {
        "de": "PNG exportieren", "fr": "Exporter en PNG", "es": "Exportar PNG", "it": "Esporta PNG", "nl": "PNG exporteren", "pt": "Exportar PNG",
        "ru": "Экспорт PNG", "cs": "Exportovat PNG", "pl": "Eksportuj PNG", "hsb": "PNG eksportować", "da": "Eksportér PNG", "nb": "Eksporter PNG",
        "hi": "PNG निर्यात करें", "zh_CN": "导出 PNG", "ja": "PNG を書き出す", "ar": "تصدير PNG", "uk": "Експортувати PNG", "be": "Экспартаваць PNG", "tr": "PNG dışa aktar",
    },
    "This drawing cannot be edited in this version.": {
        "de": "Dieses Zeichenblatt kann mit dieser Version nicht bearbeitet werden.", "fr": "Ce dessin ne peut pas être modifié dans cette version.",
        "es": "Este dibujo no se puede editar en esta versión.", "it": "Questo disegno non può essere modificato in questa versione.",
        "nl": "Deze tekening kan niet worden bewerkt in deze versie.", "pt": "Este desenho não pode ser editado nesta versão.",
        "ru": "Этот рисунок нельзя редактировать в данной версии.", "cs": "Tento výkres nelze v této verzi upravovat.",
        "pl": "Tego rysunku nie można edytować w tej wersji.", "hsb": "Tute rysowanje njeda so w tutej wersiji wobdźěłać.",
        "da": "Denne tegning kan ikke redigeres i denne version.", "nb": "Denne tegningen kan ikke redigeres i denne versjonen.",
        "hi": "इस संस्करण में इस चित्र को संपादित नहीं किया जा सकता।", "zh_CN": "此版本无法编辑这幅绘图。", "ja": "このバージョンでは、この描画を編集できません。",
        "ar": "لا يمكن تعديل هذا الرسم في هذا الإصدار.", "uk": "Цей малюнок не можна редагувати в цій версії.", "be": "Гэты малюнак нельга рэдагаваць у гэтай версіі.",
        "tr": "Bu çizim bu sürümde düzenlenemez.",
    },
    "The drawing limit has been reached.": {
        "de": "Die Zeichengrenze ist erreicht.", "fr": "La limite de dessin est atteinte.", "es": "Se ha alcanzado el límite del dibujo.",
        "it": "È stato raggiunto il limite del disegno.", "nl": "De tekenlimiet is bereikt.", "pt": "O limite do desenho foi atingido.",
        "ru": "Достигнут предел рисунка.", "cs": "Byl dosažen limit kreslení.", "pl": "Osiągnięto limit rysowania.", "hsb": "Rysowanska hranica je docpěta.",
        "da": "Tegnegrænsen er nået.", "nb": "Tegnegrensen er nådd.", "hi": "चित्रांकन की सीमा पूरी हो गई है।", "zh_CN": "已达到绘图上限。", "ja": "描画の上限に達しました。",
        "ar": "تم بلوغ حد الرسم.", "uk": "Досягнуто межі малювання.", "be": "Дасягнута мяжа малявання.", "tr": "Çizim sınırına ulaşıldı.",
    },
    "Use KDE Connect drawing tablet": {
        "de": "KDE-Connect-Zeichentablett verwenden", "fr": "Utiliser la tablette graphique KDE Connect", "es": "Usar la tableta de dibujo de KDE Connect",
        "it": "Usa la tavoletta grafica KDE Connect", "nl": "KDE Connect-tekentablet gebruiken", "pt": "Usar a mesa digitalizadora do KDE Connect",
        "ru": "Использовать графический планшет KDE Connect", "cs": "Použít grafický tablet KDE Connect", "pl": "Użyj tabletu graficznego KDE Connect",
        "hsb": "Rysowanski tablet KDE Connect wužiwać", "da": "Brug KDE Connect-tegnetablet", "nb": "Bruk KDE Connect-tegnebrett",
        "hi": "KDE Connect चित्रांकन टैबलेट का उपयोग करें", "zh_CN": "使用 KDE Connect 绘图板", "ja": "KDE Connect の描画タブレットを使う",
        "ar": "استخدام لوح الرسم في KDE Connect", "uk": "Використовувати графічний планшет KDE Connect", "be": "Выкарыстоўваць графічны планшэт KDE Connect",
        "tr": "KDE Connect çizim tabletini kullan",
    },
    "If your system KDE Connect supports tablet input, it can be used here like a normal pen.": {
        "de": "Wenn Ihr systemeigenes KDE Connect Tablett-Eingaben unterstützt, können Sie diese hier wie einen normalen Stift verwenden.",
        "fr": "Si le KDE Connect de votre système prend en charge une tablette, vous pouvez l’utiliser ici comme un stylet normal.",
        "es": "Si KDE Connect del sistema admite entrada de tableta, puede usarla aquí como un lápiz normal.",
        "it": "Se KDE Connect del sistema supporta l’input da tavoletta, puoi usarlo qui come una normale penna.",
        "nl": "Als KDE Connect op uw systeem tabletinvoer ondersteunt, kunt u die hier als een gewone pen gebruiken.",
        "pt": "Se o KDE Connect do sistema suportar entrada por mesa digitalizadora, pode usá-la aqui como uma caneta normal.",
        "ru": "Если системный KDE Connect поддерживает ввод с планшета, его можно использовать здесь как обычное перо.",
        "cs": "Pokud systémový KDE Connect podporuje vstup z tabletu, lze jej zde používat jako běžné pero.",
        "pl": "Jeśli systemowy KDE Connect obsługuje tablet, można go tutaj używać jak zwykłego pióra.",
        "hsb": "Jeli systemowy KDE Connect tabletowe zapodaće podpěruje, móžeće jo tu kaž normalne pjero wužiwać.",
        "da": "Hvis systemets KDE Connect understøtter tabletinput, kan det bruges her som en almindelig pen.",
        "nb": "Hvis systemets KDE Connect støtter nettbrettinndata, kan det brukes her som en vanlig penn.",
        "hi": "यदि आपके सिस्टम का KDE Connect टैबलेट इनपुट का समर्थन करता है, तो उसे यहाँ सामान्य पेन की तरह उपयोग किया जा सकता है।",
        "zh_CN": "如果系统的 KDE Connect 支持绘图板输入，可在此像普通画笔一样使用。",
        "ja": "システムの KDE Connect がタブレット入力に対応していれば、ここで通常のペンと同じように使用できます。",
        "ar": "إذا كان KDE Connect في نظامك يدعم إدخال اللوح، فيمكن استخدامه هنا مثل قلم عادي.",
        "uk": "Якщо системний KDE Connect підтримує введення з планшета, його можна використовувати тут як звичайне перо.",
        "be": "Калі сістэмны KDE Connect падтрымлівае ўвод з планшэта, яго можна выкарыстоўваць тут як звычайнае пяро.",
        "tr": "Sisteminizdeki KDE Connect tablet girişini destekliyorsa burada normal bir kalem gibi kullanılabilir.",
    },
    "Enable tablet input here, then open the drawing tablet in KDE Connect on the phone.": {
        "de": "Aktivieren Sie hier die Tablett-Eingabe und öffnen Sie dann das Zeichentablett in KDE Connect auf dem Telefon.",
        "fr": "Activez ici l’entrée tablette, puis ouvrez la tablette graphique dans KDE Connect sur le téléphone.",
        "es": "Active aquí la entrada de tableta y abra después la tableta de dibujo en KDE Connect del teléfono.",
        "it": "Abilita qui l’input da tavoletta, quindi apri la tavoletta grafica in KDE Connect sul telefono.",
        "nl": "Schakel hier tabletinvoer in en open daarna de tekentablet in KDE Connect op de telefoon.",
        "pt": "Ative aqui a entrada por mesa digitalizadora e depois abra a mesa digitalizadora no KDE Connect do telefone.",
        "ru": "Включите здесь ввод с планшета, затем откройте графический планшет в KDE Connect на телефоне.",
        "cs": "Zde povolte vstup z tabletu a poté otevřete grafický tablet v KDE Connect na telefonu.",
        "pl": "Włącz tutaj wejście tabletu, a następnie otwórz tablet graficzny w KDE Connect na telefonie.",
        "hsb": "Zmóžńće tu tabletowe zapodaće a wočińće potom rysowanski tablet w KDE Connect na telefonje.",
        "da": "Aktivér tabletinput her, og åbn derefter tegnetabletten i KDE Connect på telefonen.",
        "nb": "Aktiver nettbrettinndata her, og åpne deretter tegnebrettet i KDE Connect på telefonen.",
        "hi": "यहाँ टैबलेट इनपुट चालू करें, फिर फ़ोन पर KDE Connect में चित्रांकन टैबलेट खोलें।",
        "zh_CN": "在此启用绘图板输入，然后在手机的 KDE Connect 中打开绘图板。",
        "ja": "ここでタブレット入力を有効にしてから、電話の KDE Connect で描画タブレットを開いてください。",
        "ar": "فعّل إدخال اللوح هنا، ثم افتح لوح الرسم في KDE Connect على الهاتف.",
        "uk": "Увімкніть тут введення з планшета, потім відкрийте графічний планшет у KDE Connect на телефоні.",
        "be": "Уключыце тут увод з планшэта, затым адкрыйце графічны планшэт у KDE Connect на тэлефоне.",
        "tr": "Burada tablet girişini etkinleştirin, ardından telefondaki KDE Connect’te çizim tabletini açın.",
    },
    "Automatically dismiss anniversary reminders": {
        "de": "Jahrestagserinnerungen automatisch ausblenden", "fr": "Masquer automatiquement les rappels d’anniversaire",
        "es": "Ocultar automáticamente los recordatorios de aniversarios", "it": "Nascondi automaticamente i promemoria degli anniversari",
        "nl": "Herinneringen aan verjaardagen en jubilea automatisch verbergen", "pt": "Ocultar automaticamente os lembretes de aniversários",
        "ru": "Автоматически скрывать напоминания о годовщинах", "cs": "Automaticky skrývat připomínky výročí",
        "pl": "Automatycznie ukrywaj przypomnienia o rocznicach", "hsb": "Dopomnjeća na róčnicy awtomatisce schować",
        "da": "Skjul automatisk påmindelser om mærkedage", "nb": "Skjul påminnelser om merkedager automatisk",
        "hi": "वर्षगाँठ के अनुस्मारक अपने आप छिपाएँ", "zh_CN": "自动隐藏纪念日提醒", "ja": "記念日のリマインダーを自動的に非表示にする",
        "ar": "إخفاء تذكيرات الذكريات السنوية تلقائيًا", "uk": "Автоматично приховувати нагадування про річниці",
        "be": "Аўтаматычна хаваць напаміны пра гадавіны", "tr": "Yıldönümü hatırlatmalarını otomatik gizle",
    },
    "By default, anniversary reminders stay visible until you close them. This setting is independent of appointment reminders.": {
        "de": "Jahrestagserinnerungen bleiben standardmäßig sichtbar, bis Sie sie schließen. Diese Einstellung ist unabhängig von Terminerinnerungen.",
        "fr": "Par défaut, les rappels d’anniversaire restent visibles jusqu’à leur fermeture. Ce réglage est indépendant des rappels de rendez-vous.",
        "es": "De forma predeterminada, los recordatorios de aniversarios permanecen visibles hasta que los cierre. Este ajuste es independiente de los recordatorios de citas.",
        "it": "Per impostazione predefinita, i promemoria degli anniversari restano visibili finché non vengono chiusi. Questa impostazione è indipendente dai promemoria degli appuntamenti.",
        "nl": "Herinneringen aan verjaardagen en jubilea blijven standaard zichtbaar totdat u ze sluit. Deze instelling staat los van afspraakherinneringen.",
        "pt": "Por predefinição, os lembretes de aniversários permanecem visíveis até serem fechados. Esta definição é independente dos lembretes de compromissos.",
        "ru": "По умолчанию напоминания о годовщинах остаются видимыми, пока вы их не закроете. Эта настройка не зависит от напоминаний о встречах.",
        "cs": "Připomínky výročí ve výchozím nastavení zůstávají viditelné, dokud je nezavřete. Toto nastavení je nezávislé na připomínkách schůzek.",
        "pl": "Domyślnie przypomnienia o rocznicach pozostają widoczne, dopóki ich nie zamkniesz. To ustawienie jest niezależne od przypomnień o spotkaniach.",
        "hsb": "Dopomnjeća na róčnicy standardnje widźomne wostanu, doniž je njezačinjeće. Tute nastajenje je njewotwisne wot dopomnjećow na terminy.",
        "da": "Påmindelser om mærkedage forbliver som standard synlige, indtil du lukker dem. Denne indstilling er uafhængig af aftalepåmindelser.",
        "nb": "Påminnelser om merkedager forblir som standard synlige til du lukker dem. Denne innstillingen er uavhengig av avtalepåminnelser.",
        "hi": "डिफ़ॉल्ट रूप से, वर्षगाँठ के अनुस्मारक तब तक दिखाई देते हैं जब तक आप उन्हें बंद नहीं करते। यह सेटिंग नियुक्ति के अनुस्मारकों से स्वतंत्र है।",
        "zh_CN": "默认情况下，纪念日提醒会一直显示，直到您手动关闭。此设置独立于日程提醒。",
        "ja": "記念日のリマインダーは、標準では閉じるまで表示されます。この設定は予定のリマインダーとは独立しています。",
        "ar": "تبقى تذكيرات الذكريات السنوية ظاهرة افتراضيًا حتى تغلقها. هذا الإعداد مستقل عن تذكيرات المواعيد.",
        "uk": "Типово нагадування про річниці залишаються видимими, доки ви їх не закриєте. Це налаштування не залежить від нагадувань про зустрічі.",
        "be": "Прадвызначана напаміны пра гадавіны застаюцца бачнымі, пакуль вы іх не закрыеце. Гэта налада не залежыць ад напамінаў пра сустрэчы.",
        "tr": "Varsayılan olarak yıldönümü hatırlatmaları siz kapatana kadar görünür kalır. Bu ayar randevu hatırlatmalarından bağımsızdır.",
    },
    "Phone contacts (KDE Connect)": {
        "de": "Telefonkontakte (KDE Connect)", "fr": "Contacts du téléphone (KDE Connect)", "es": "Contactos del teléfono (KDE Connect)",
        "it": "Contatti del telefono (KDE Connect)", "nl": "Telefooncontacten (KDE Connect)", "pt": "Contactos do telefone (KDE Connect)",
        "ru": "Контакты телефона (KDE Connect)", "cs": "Kontakty telefonu (KDE Connect)", "pl": "Kontakty telefonu (KDE Connect)",
        "hsb": "Telefonowe kontakty (KDE Connect)", "da": "Telefonkontakter (KDE Connect)", "nb": "Telefonkontakter (KDE Connect)",
        "hi": "फ़ोन संपर्क (KDE Connect)", "zh_CN": "手机联系人（KDE Connect）", "ja": "電話の連絡先 (KDE Connect)",
        "ar": "جهات اتصال الهاتف (KDE Connect)", "uk": "Контакти телефону (KDE Connect)", "be": "Кантакты тэлефона (KDE Connect)",
        "tr": "Telefon kişileri (KDE Connect)",
    },
    "Preview contacts from the paired phone. Changes are saved only in Organizer; no contacts are deleted.": {
        "de": "Kontakte des gekoppelten Telefons vorab prüfen. Änderungen werden nur im Organizer gespeichert; es werden keine Kontakte gelöscht.",
        "fr": "Prévisualisez les contacts du téléphone associé. Les modifications sont enregistrées uniquement dans Organizer ; aucun contact n’est supprimé.",
        "es": "Revise los contactos del teléfono vinculado. Los cambios se guardan solo en Organizer; no se elimina ningún contacto.",
        "it": "Visualizza in anteprima i contatti del telefono associato. Le modifiche vengono salvate solo in Organizer; nessun contatto viene eliminato.",
        "nl": "Bekijk vooraf de contacten van de gekoppelde telefoon. Wijzigingen worden alleen in Organizer opgeslagen; er worden geen contacten verwijderd.",
        "pt": "Pré-visualize os contactos do telefone emparelhado. As alterações são guardadas apenas no Organizer; nenhum contacto é eliminado.",
        "ru": "Просмотрите контакты сопряжённого телефона. Изменения сохраняются только в Organizer; контакты не удаляются.",
        "cs": "Prohlédněte si kontakty spárovaného telefonu. Změny se ukládají pouze do Organizeru; žádné kontakty se nemažou.",
        "pl": "Przejrzyj kontakty sparowanego telefonu. Zmiany są zapisywane tylko w Organizerze; żadne kontakty nie są usuwane.",
        "hsb": "Přepruwujće kontakty spřaženeho telefona. Změny so jenož w Organizer składuja; žane kontakty so njezhašeja.",
        "da": "Forhåndsvis kontakter fra den parrede telefon. Ændringer gemmes kun i Organizer; ingen kontakter slettes.",
        "nb": "Forhåndsvis kontakter fra den parede telefonen. Endringer lagres bare i Organizer; ingen kontakter slettes.",
        "hi": "युग्मित फ़ोन के संपर्कों का पूर्वावलोकन करें। बदलाव केवल Organizer में सहेजे जाते हैं; कोई संपर्क नहीं हटाया जाता।",
        "zh_CN": "预览已配对手机的联系人。更改仅保存在 Organizer 中，不会删除任何联系人。",
        "ja": "ペアリング済みの電話の連絡先をプレビューします。変更は Organizer にのみ保存され、連絡先は削除されません。",
        "ar": "عاين جهات اتصال الهاتف المقترن. تُحفظ التغييرات في Organizer فقط؛ ولا تُحذف أي جهة اتصال.",
        "uk": "Перегляньте контакти спареного телефону. Зміни зберігаються лише в Organizer; контакти не видаляються.",
        "be": "Праглядзіце кантакты спалучанага тэлефона. Змены захоўваюцца толькі ў Organizer; кантакты не выдаляюцца.",
        "tr": "Eşleştirilmiş telefonun kişilerini önizleyin. Değişiklikler yalnızca Organizer’da kaydedilir; hiçbir kişi silinmez.",
    },
    "Please wait …": {
        "de": "Bitte warten …", "fr": "Veuillez patienter…", "es": "Espere…", "it": "Attendere…", "nl": "Even geduld …",
        "pt": "Aguarde…", "ru": "Подождите…", "cs": "Čekejte…", "pl": "Proszę czekać…", "hsb": "Prošu čakajće …",
        "da": "Vent venligst …", "nb": "Vennligst vent …", "hi": "कृपया प्रतीक्षा करें…", "zh_CN": "请稍候…", "ja": "お待ちください…",
        "ar": "يُرجى الانتظار…", "uk": "Зачекайте…", "be": "Пачакайце…", "tr": "Lütfen bekleyin …",
    },
    "Additional information": {
        "de": "Zusätzliche Angaben", "fr": "Informations supplémentaires", "es": "Información adicional", "it": "Informazioni aggiuntive",
        "nl": "Aanvullende informatie", "pt": "Informações adicionais", "ru": "Дополнительные сведения", "cs": "Další informace",
        "pl": "Dodatkowe informacje", "hsb": "Přidatne informacije", "da": "Yderligere oplysninger", "nb": "Tilleggsinformasjon",
        "hi": "अतिरिक्त जानकारी", "zh_CN": "附加信息", "ja": "追加情報", "ar": "معلومات إضافية", "uk": "Додаткові відомості",
        "be": "Дадатковыя звесткі", "tr": "Ek bilgiler",
    },
    "The Windows installer includes the manual.": {
        "de": "Das Handbuch ist im Windows-Installationsprogramm enthalten.",
        "fr": "Le programme d’installation Windows inclut le manuel.",
        "es": "El instalador de Windows incluye el manual.",
        "it": "Il programma di installazione per Windows include il manuale.",
        "nl": "Het Windows-installatieprogramma bevat de handleiding.",
        "pt": "O instalador do Windows inclui o manual.",
        "ru": "Руководство входит в установщик для Windows.",
        "cs": "Instalační program pro Windows obsahuje příručku.",
        "pl": "Instalator systemu Windows zawiera podręcznik.",
        "hsb": "Instalaciski program za Windows wobsahuje přiručku.",
        "da": "Installationsprogrammet til Windows indeholder vejledningen.",
        "nb": "Installasjonsprogrammet for Windows inneholder håndboken.",
        "hi": "Windows इंस्टॉलर में पुस्तिका शामिल है।",
        "zh_CN": "Windows 安装程序包含用户手册。",
        "ja": "Windows インストーラーにはマニュアルが含まれています。",
        "ar": "يتضمن برنامج تثبيت Windows الدليل.",
        "uk": "Посібник входить до інсталятора для Windows.",
        "be": "Дапаможнік уваходзіць ва ўсталёўшчык для Windows.",
        "tr": "Windows yükleyicisi kılavuzu içerir.",
    },
    "Google requires browser sign-in. Use Internet accounts in Settings.": {
        "de": "Google benötigt eine Anmeldung im Browser. Verwenden Sie Internetkonten in den Einstellungen.",
        "fr": "Google exige une connexion dans le navigateur. Utilisez Comptes en ligne dans les paramètres.",
        "es": "Google requiere iniciar sesión en el navegador. Utilice Cuentas de Internet en los ajustes.",
        "it": "Google richiede l’accesso nel browser. Utilizzare Account Internet nelle impostazioni.",
        "nl": "Google vereist aanmelding in de browser. Gebruik Internetaccounts in de instellingen.",
        "pt": "O Google requer início de sessão no navegador. Utilize Contas de Internet nas definições.",
        "ru": "Google требует входа через браузер. Откройте Интернет-аккаунты в настройках.",
        "cs": "Google vyžaduje přihlášení v prohlížeči. Použijte Internetové účty v nastavení.",
        "pl": "Google wymaga logowania w przeglądarce. Użyj Kont internetowych w ustawieniach.",
        "hsb": "Google sej přizjewjenje we wobhladowaku žada. Wužiwajće Internetne konta w nastajenjach.",
        "da": "Google kræver login i browseren. Brug Internetkonti i indstillingerne.",
        "nb": "Google krever innlogging i nettleseren. Bruk Internettkontoer i innstillingene.",
        "hi": "Google के लिए ब्राउज़र में साइन इन करना आवश्यक है। सेटिंग्स में इंटरनेट खाते उपयोग करें।",
        "zh_CN": "Google 需要在浏览器中登录。请使用设置中的“互联网账户”。",
        "ja": "Google にはブラウザーでのログインが必要です。設定の「インターネットアカウント」を使用してください。",
        "ar": "يتطلب Google تسجيل الدخول في المتصفح. استخدم حسابات الإنترنت في الإعدادات.",
        "uk": "Google потребує входу через браузер. Використовуйте Інтернет-облікові записи в налаштуваннях.",
        "be": "Google патрабуе ўваходу праз браўзер. Выкарыстоўвайце Інтэрнэт-акаўнты ў наладах.",
        "tr": "Google, tarayıcıda oturum açılmasını gerektirir. Ayarlardaki İnternet hesaplarını kullanın.",
    },
    "Enter your email address.": {
        "de": "Geben Sie Ihre E-Mail-Adresse ein.", "fr": "Saisissez votre adresse e-mail.",
        "es": "Introduzca su dirección de correo electrónico.", "it": "Inserire l’indirizzo email.",
        "nl": "Voer uw e-mailadres in.", "pt": "Introduza o seu endereço de e-mail.",
        "ru": "Введите адрес электронной почты.", "cs": "Zadejte svou e-mailovou adresu.",
        "pl": "Wpisz swój adres e-mail.", "hsb": "Zapodajće swoju e-mejlowu adresu.",
        "da": "Indtast din mailadresse.", "nb": "Skriv inn e-postadressen din.",
        "hi": "अपना ईमेल पता दर्ज करें।", "zh_CN": "请输入您的邮箱地址。", "ja": "メールアドレスを入力してください。",
        "ar": "أدخل عنوان بريدك الإلكتروني.", "uk": "Введіть свою адресу електронної пошти.",
        "be": "Увядзіце свой адрас электроннай пошты.", "tr": "E-posta adresinizi girin.",
    },
    "Internet accounts": {
        "de": "Internetkonten", "fr": "Comptes en ligne", "es": "Cuentas de Internet", "it": "Account Internet",
        "nl": "Internetaccounts", "pt": "Contas de Internet", "ru": "Интернет-аккаунты", "cs": "Internetové účty",
        "pl": "Konta internetowe", "hsb": "Internetne konta", "da": "Internetkonti", "nb": "Internettkontoer",
        "hi": "इंटरनेट खाते", "zh_CN": "互联网账户", "ja": "インターネットアカウント", "ar": "حسابات الإنترنت",
        "uk": "Інтернет-облікові записи", "be": "Інтэрнэт-акаўнты", "tr": "İnternet hesapları",
    },
    "Magnolie manages the account connection in the background.": {
        "de": "Magnolie verwaltet die Kontoverbindung im Hintergrund.",
        "fr": "Magnolie gère la connexion au compte en arrière-plan.",
        "es": "Magnolie gestiona la conexión de la cuenta en segundo plano.",
        "it": "Magnolie gestisce la connessione dell’account in background.",
        "nl": "Magnolie beheert de accountverbinding op de achtergrond.",
        "pt": "O Magnolie gere a ligação à conta em segundo plano.",
        "ru": "Magnolie управляет подключением к аккаунту в фоновом режиме.",
        "cs": "Magnolie spravuje připojení k účtu na pozadí.",
        "pl": "Magnolie zarządza połączeniem z kontem w tle.",
        "hsb": "Magnolie zwisk z kontom w pozadku rjaduje.",
        "da": "Magnolie håndterer kontoforbindelsen i baggrunden.",
        "nb": "Magnolie håndterer kontotilkoblingen i bakgrunnen.",
        "hi": "Magnolie पृष्ठभूमि में खाते का कनेक्शन संभालता है।",
        "zh_CN": "Magnolie 在后台管理账户连接。", "ja": "Magnolie がバックグラウンドでアカウント接続を管理します。",
        "ar": "يدير Magnolie اتصال الحساب في الخلفية.",
        "uk": "Magnolie керує підключенням до облікового запису у фоновому режимі.",
        "be": "Magnolie кіруе злучэннем з уліковым запісам у фонавым рэжыме.",
        "tr": "Magnolie hesap bağlantısını arka planda yönetir.",
    },
    "Preparing account sign-in …": {
        "de": "Kontoanmeldung wird vorbereitet …", "fr": "Préparation de la connexion au compte…",
        "es": "Preparando el inicio de sesión…", "it": "Preparazione dell’accesso all’account…",
        "nl": "Accountaanmelding voorbereiden …", "pt": "A preparar o início de sessão…",
        "ru": "Подготовка входа в аккаунт…", "cs": "Příprava přihlášení k účtu…",
        "pl": "Przygotowywanie logowania do konta…", "hsb": "Přizjewjenje pola konta so přihotuje …",
        "da": "Forbereder login til kontoen …", "nb": "Forbereder kontoinnlogging …",
        "hi": "खाते में साइन इन करने की तैयारी…", "zh_CN": "正在准备账户登录…", "ja": "アカウントへのログインを準備中…",
        "ar": "جارٍ تحضير تسجيل الدخول إلى الحساب…", "uk": "Підготовка входу до облікового запису…",
        "be": "Падрыхтоўка ўваходу ва ўліковы запіс…", "tr": "Hesap oturumu hazırlanıyor…",
    },
    "Enter your Google email address.": {
        "de": "Geben Sie Ihre Google-E-Mail-Adresse ein.", "fr": "Saisissez votre adresse e-mail Google.",
        "es": "Introduzca su dirección de correo de Google.", "it": "Inserire l’indirizzo email Google.",
        "nl": "Voer uw Google-e-mailadres in.", "pt": "Introduza o seu endereço de e-mail Google.",
        "ru": "Введите адрес электронной почты Google.", "cs": "Zadejte svou e-mailovou adresu Google.",
        "pl": "Wpisz swój adres e-mail Google.", "hsb": "Zapodajće swoju e-mejlowu adresu Google.",
        "da": "Indtast din Google-mailadresse.", "nb": "Skriv inn Google-e-postadressen din.",
        "hi": "अपना Google ईमेल पता दर्ज करें।", "zh_CN": "请输入您的 Google 邮箱地址。", "ja": "Google のメールアドレスを入力してください。",
        "ar": "أدخل عنوان بريدك الإلكتروني في Google.", "uk": "Введіть свою адресу електронної пошти Google.",
        "be": "Увядзіце свой адрас электроннай пошты Google.", "tr": "Google e-posta adresinizi girin.",
    },
    "Account sign-in could not be started. Please try again.": {
        "de": "Die Kontoanmeldung konnte nicht gestartet werden. Bitte versuchen Sie es erneut.",
        "fr": "La connexion au compte n’a pas pu démarrer. Veuillez réessayer.",
        "es": "No se pudo iniciar el acceso a la cuenta. Inténtelo de nuevo.",
        "it": "Impossibile avviare l’accesso all’account. Riprovare.",
        "nl": "De accountaanmelding kon niet worden gestart. Probeer het opnieuw.",
        "pt": "Não foi possível iniciar a sessão na conta. Tente novamente.",
        "ru": "Не удалось начать вход в аккаунт. Повторите попытку.",
        "cs": "Přihlášení k účtu se nepodařilo spustit. Zkuste to znovu.",
        "pl": "Nie udało się rozpocząć logowania do konta. Spróbuj ponownie.",
        "hsb": "Přizjewjenje pola konta njeda so startować. Spytajće prošu hišće raz.",
        "da": "Login til kontoen kunne ikke startes. Prøv igen.",
        "nb": "Kontoinnloggingen kunne ikke startes. Prøv igjen.",
        "hi": "खाते में साइन इन शुरू नहीं हो सका। कृपया फिर से प्रयास करें।",
        "zh_CN": "无法启动账户登录。请重试。", "ja": "アカウントへのログインを開始できませんでした。もう一度お試しください。",
        "ar": "تعذر بدء تسجيل الدخول إلى الحساب. يُرجى المحاولة مجددًا.",
        "uk": "Не вдалося розпочати вхід до облікового запису. Спробуйте ще раз.",
        "be": "Не ўдалося пачаць уваход ва ўліковы запіс. Паспрабуйце яшчэ раз.",
        "tr": "Hesap oturumu başlatılamadı. Lütfen tekrar deneyin.",
    },
    "Set up Thunderbird connection": {
        "de": "Thunderbird-Verbindung einrichten", "fr": "Configurer la connexion Thunderbird", "es": "Configurar la conexión con Thunderbird",
        "it": "Configurare la connessione Thunderbird", "nl": "Thunderbird-verbinding instellen", "pt": "Configurar a ligação ao Thunderbird",
        "ru": "Настроить подключение к Thunderbird", "cs": "Nastavit připojení k Thunderbirdu", "pl": "Skonfiguruj połączenie z Thunderbirdem",
        "hsb": "Zwisk z Thunderbird zarjadować", "da": "Opsæt Thunderbird-forbindelse", "nb": "Sett opp Thunderbird-tilkobling",
        "hi": "Thunderbird कनेक्शन सेट करें", "zh_CN": "设置 Thunderbird 连接", "ja": "Thunderbird 接続を設定",
        "ar": "إعداد الاتصال بـ Thunderbird", "uk": "Налаштувати підключення до Thunderbird", "be": "Наладзіць злучэнне з Thunderbird", "tr": "Thunderbird bağlantısını ayarla",
    },
    "Thunderbird manages Google sign-in. Select its calendars and address books above.": {
        "de": "Thunderbird übernimmt die Google-Anmeldung. Wählen Sie dessen Kalender und Adressbücher oben aus.",
        "fr": "Thunderbird gère la connexion Google. Sélectionnez ses agendas et carnets d’adresses ci-dessus.",
        "es": "Thunderbird gestiona el inicio de sesión de Google. Seleccione sus calendarios y libretas de direcciones arriba.",
        "it": "Thunderbird gestisce l’accesso a Google. Selezionare i suoi calendari e le rubriche qui sopra.",
        "nl": "Thunderbird verzorgt de Google-aanmelding. Selecteer hierboven de agenda’s en adresboeken.",
        "pt": "O Thunderbird gere o início de sessão no Google. Selecione os seus calendários e livros de endereços acima.",
        "ru": "Thunderbird управляет входом в Google. Выберите его календари и адресные книги выше.",
        "cs": "Thunderbird zajišťuje přihlášení ke Googlu. Výše vyberte jeho kalendáře a adresáře.",
        "pl": "Thunderbird obsługuje logowanie do Google. Wybierz powyżej jego kalendarze i książki adresowe.",
        "hsb": "Thunderbird přizjewjenje pola Google přewozmje. Wubjerće horjeka jeho protyki a adresniki.",
        "da": "Thunderbird håndterer Google-login. Vælg dets kalendere og adressebøger ovenfor.",
        "nb": "Thunderbird håndterer Google-innlogging. Velg kalenderne og adressebøkene ovenfor.",
        "hi": "Thunderbird Google साइन-इन संभालता है। ऊपर उसके कैलेंडर और पता पुस्तिकाएँ चुनें।",
        "zh_CN": "Thunderbird 负责 Google 登录。请在上方选择其日历和通讯录。",
        "ja": "Thunderbird が Google へのログインを管理します。上でカレンダーとアドレス帳を選択してください。",
        "ar": "يتولى Thunderbird تسجيل الدخول إلى Google. اختر تقاويمه ودفاتر عناوينه أعلاه.",
        "uk": "Thunderbird керує входом у Google. Виберіть його календарі й адресні книги вище.",
        "be": "Thunderbird кіруе ўваходам у Google. Выберыце яго календары і адрасныя кнігі вышэй.",
        "tr": "Google oturum açma işlemini Thunderbird yönetir. Yukarıdan takvimlerini ve adres defterlerini seçin.",
    },
    "Google requires browser sign-in. Use Thunderbird to manage this account.": {
        "de": "Google benötigt eine Anmeldung im Browser. Verwalten Sie dieses Konto über Thunderbird.",
        "fr": "Google exige une connexion dans le navigateur. Gérez ce compte avec Thunderbird.",
        "es": "Google requiere iniciar sesión en el navegador. Gestione esta cuenta con Thunderbird.",
        "it": "Google richiede l’accesso nel browser. Gestire questo account con Thunderbird.",
        "nl": "Google vereist aanmelding in de browser. Beheer dit account via Thunderbird.",
        "pt": "O Google requer início de sessão no navegador. Utilize o Thunderbird para gerir esta conta.",
        "ru": "Google требует входа через браузер. Управляйте этой учётной записью через Thunderbird.",
        "cs": "Google vyžaduje přihlášení v prohlížeči. Spravujte tento účet v Thunderbirdu.",
        "pl": "Google wymaga logowania w przeglądarce. Zarządzaj tym kontem w Thunderbirdzie.",
        "hsb": "Google sej přizjewjenje we wobhladowaku žada. Zarjadujće tute konto přez Thunderbird.",
        "da": "Google kræver login i browseren. Brug Thunderbird til at administrere denne konto.",
        "nb": "Google krever innlogging i nettleseren. Bruk Thunderbird til å administrere denne kontoen.",
        "hi": "Google के लिए ब्राउज़र में साइन इन करना आवश्यक है। इस खाते को Thunderbird में प्रबंधित करें।",
        "zh_CN": "Google 需要在浏览器中登录。请使用 Thunderbird 管理此账户。",
        "ja": "Google にはブラウザーでのログインが必要です。このアカウントは Thunderbird で管理してください。",
        "ar": "يتطلب Google تسجيل الدخول في المتصفح. استخدم Thunderbird لإدارة هذا الحساب.",
        "uk": "Google потребує входу через браузер. Керуйте цим обліковим записом через Thunderbird.",
        "be": "Google патрабуе ўваходу праз браўзер. Кіруйце гэтым уліковым запісам праз Thunderbird.",
        "tr": "Google, tarayıcıda oturum açılmasını gerektirir. Bu hesabı Thunderbird üzerinden yönetin.",
    },
    "Thunderbird could not complete the request. Check the account in Thunderbird.": {
        "de": "Thunderbird konnte die Anfrage nicht abschließen. Prüfen Sie das Konto in Thunderbird.",
        "fr": "Thunderbird n’a pas pu terminer la requête. Vérifiez le compte dans Thunderbird.",
        "es": "Thunderbird no pudo completar la solicitud. Compruebe la cuenta en Thunderbird.",
        "it": "Thunderbird non ha completato la richiesta. Controllare l’account in Thunderbird.",
        "nl": "Thunderbird kon het verzoek niet voltooien. Controleer het account in Thunderbird.",
        "pt": "O Thunderbird não conseguiu concluir o pedido. Verifique a conta no Thunderbird.",
        "ru": "Thunderbird не смог выполнить запрос. Проверьте учётную запись в Thunderbird.",
        "cs": "Thunderbird nemohl dokončit požadavek. Zkontrolujte účet v Thunderbirdu.",
        "pl": "Thunderbird nie mógł wykonać żądania. Sprawdź konto w Thunderbirdzie.",
        "hsb": "Thunderbird njemóžeše naprašowanje dokónčić. Přepruwujće konto w Thunderbird.",
        "da": "Thunderbird kunne ikke fuldføre anmodningen. Kontrollér kontoen i Thunderbird.",
        "nb": "Thunderbird kunne ikke fullføre forespørselen. Kontroller kontoen i Thunderbird.",
        "hi": "Thunderbird अनुरोध पूरा नहीं कर सका। Thunderbird में खाता जाँचें।",
        "zh_CN": "Thunderbird 无法完成请求。请在 Thunderbird 中检查账户。",
        "ja": "Thunderbird は要求を完了できませんでした。Thunderbird でアカウントを確認してください。",
        "ar": "تعذر على Thunderbird إكمال الطلب. تحقق من الحساب في Thunderbird.",
        "uk": "Thunderbird не зміг виконати запит. Перевірте обліковий запис у Thunderbird.",
        "be": "Thunderbird не змог выканаць запыт. Праверце ўліковы запіс у Thunderbird.",
        "tr": "Thunderbird isteği tamamlayamadı. Thunderbird içindeki hesabı kontrol edin.",
    },
    "Install the highlighted extension in Thunderbird via Add-ons and Themes → Install Add-on From File. Keep Thunderbird open.": {
        "de": "Installieren Sie die markierte Erweiterung in Thunderbird über Add-ons und Themes → Add-on aus Datei installieren. Lassen Sie Thunderbird geöffnet.",
        "fr": "Installez l’extension sélectionnée dans Thunderbird via Modules complémentaires et thèmes → Installer un module depuis un fichier. Gardez Thunderbird ouvert.",
        "es": "Instale la extensión seleccionada en Thunderbird mediante Complementos y temas → Instalar complemento desde archivo. Mantenga Thunderbird abierto.",
        "it": "Installare l’estensione selezionata in Thunderbird tramite Componenti aggiuntivi e temi → Installa componente aggiuntivo da file. Lasciare Thunderbird aperto.",
        "nl": "Installeer de geselecteerde extensie in Thunderbird via Add-ons en thema’s → Add-on installeren via bestand. Laat Thunderbird open.",
        "pt": "Instale a extensão selecionada no Thunderbird em Extras e temas → Instalar extra a partir de ficheiro. Mantenha o Thunderbird aberto.",
        "ru": "Установите выделенное расширение в Thunderbird через Дополнения и темы → Установить дополнение из файла. Оставьте Thunderbird открытым.",
        "cs": "Nainstalujte označené rozšíření v Thunderbirdu přes Doplňky a motivy vzhledu → Instalovat doplněk ze souboru. Nechte Thunderbird otevřený.",
        "pl": "Zainstaluj zaznaczone rozszerzenie w Thunderbirdzie przez Dodatki i motywy → Zainstaluj dodatek z pliku. Pozostaw Thunderbirda otwartego.",
        "hsb": "Instalujće markěrowane rozšěrjenje w Thunderbird přez Přidatki a drasty → Přidatk z dataje instalować. Wostajće Thunderbird wočinjeny.",
        "da": "Installér den markerede udvidelse i Thunderbird via Tilføjelser og temaer → Installér tilføjelse fra fil. Lad Thunderbird være åben.",
        "nb": "Installer den markerte utvidelsen i Thunderbird via Utvidelser og temaer → Installer utvidelse fra fil. Hold Thunderbird åpen.",
        "hi": "Thunderbird में ऐड-ऑन और थीम → फ़ाइल से ऐड-ऑन स्थापित करें द्वारा चुना गया एक्सटेंशन स्थापित करें। Thunderbird खुला रखें।",
        "zh_CN": "在 Thunderbird 中通过“附加组件和主题 → 从文件安装附加组件”安装选中的扩展。请保持 Thunderbird 运行。",
        "ja": "Thunderbird の「アドオンとテーマ → ファイルからアドオンをインストール」で選択された拡張機能をインストールしてください。Thunderbird は開いたままにしてください。",
        "ar": "ثبّت الإضافة المحددة في Thunderbird عبر الإضافات والسمات ← تثبيت إضافة من ملف. أبقِ Thunderbird مفتوحًا.",
        "uk": "Установіть виділене розширення в Thunderbird через Додатки й теми → Установити додаток із файлу. Залиште Thunderbird відкритим.",
        "be": "Усталюйце вылучанае пашырэнне ў Thunderbird праз Дадаткі і тэмы → Усталяваць дадатак з файла. Пакіньце Thunderbird адкрытым.",
        "tr": "Seçili uzantıyı Thunderbird’de Eklentiler ve Temalar → Dosyadan Eklenti Yükle yoluyla yükleyin. Thunderbird’ü açık tutun.",
    },
    "Show successful synchronization notifications (errors are always shown)": {
        "de": "Erfolgreichen Abgleich melden (Fehler werden immer angezeigt)",
        "fr": "Signaler les synchronisations réussies (les erreurs sont toujours affichées)",
        "es": "Notificar las sincronizaciones correctas (los errores siempre se muestran)",
        "it": "Notificare le sincronizzazioni riuscite (gli errori vengono sempre mostrati)",
        "nl": "Geslaagde synchronisaties melden (fouten worden altijd getoond)",
        "pt": "Notificar sincronizações bem-sucedidas (os erros são sempre apresentados)",
        "ru": "Уведомлять об успешной синхронизации (ошибки показываются всегда)",
        "cs": "Oznamovat úspěšnou synchronizaci (chyby se zobrazují vždy)",
        "pl": "Powiadamiaj o udanej synchronizacji (błędy są zawsze wyświetlane)",
        "hsb": "Wuspěšnu synchronizaciju zdźělić (zmylki so přeco pokazuja)",
        "da": "Vis beskeder om vellykket synkronisering (fejl vises altid)",
        "nb": "Vis meldinger om vellykket synkronisering (feil vises alltid)",
        "hi": "सफल सिंक्रनाइज़ेशन की सूचनाएँ दिखाएँ (त्रुटियाँ हमेशा दिखाई जाती हैं)",
        "zh_CN": "显示同步成功通知（始终显示错误）",
        "ja": "同期成功の通知を表示する（エラーは常に表示）",
        "ar": "إظهار إشعارات نجاح المزامنة (تظهر الأخطاء دائمًا)",
        "uk": "Сповіщати про успішну синхронізацію (помилки показуються завжди)",
        "be": "Паведамляць пра паспяховую сінхранізацыю (памылкі паказваюцца заўсёды)",
        "tr": "Başarılı eşitlemeleri bildir (hatalar her zaman gösterilir)",
    },
    "DAV account": {
        "de": "DAV-Konto", "fr": "Compte DAV", "es": "Cuenta DAV", "it": "Account DAV",
        "nl": "DAV-account", "pt": "Conta DAV", "ru": "Учётная запись DAV", "cs": "Účet DAV",
        "pl": "Konto DAV", "hsb": "DAV-konto", "da": "DAV-konto", "nb": "DAV-konto",
        "hi": "DAV खाता", "zh_CN": "DAV 账户", "ja": "DAV アカウント", "ar": "حساب DAV",
        "uk": "Обліковий запис DAV", "be": "Уліковы запіс DAV", "tr": "DAV hesabı",
    },
    "Account type": {
        "de": "Kontoart", "fr": "Type de compte", "es": "Tipo de cuenta", "it": "Tipo di account",
        "nl": "Accounttype", "pt": "Tipo de conta", "ru": "Тип учётной записи", "cs": "Typ účtu",
        "pl": "Typ konta", "hsb": "Kontowy typ", "da": "Kontotype", "nb": "Kontotype",
        "hi": "खाते का प्रकार", "zh_CN": "账户类型", "ja": "アカウントの種類", "ar": "نوع الحساب",
        "uk": "Тип облікового запису", "be": "Тып уліковага запісу", "tr": "Hesap türü",
    },
    "Use the DAV address provided by your service.": {
        "de": "Verwenden Sie die DAV-Adresse Ihres Anbieters.",
        "fr": "Utilisez l’adresse DAV fournie par votre service.",
        "es": "Utilice la dirección DAV proporcionada por su servicio.",
        "it": "Utilizzare l’indirizzo DAV fornito dal servizio.",
        "nl": "Gebruik het DAV-adres van uw aanbieder.",
        "pt": "Utilize o endereço DAV fornecido pelo seu serviço.",
        "ru": "Используйте адрес DAV, предоставленный вашим сервисом.",
        "cs": "Použijte adresu DAV od svého poskytovatele.",
        "pl": "Użyj adresu DAV podanego przez dostawcę usługi.",
        "hsb": "Wužiwajće DAV-adresu swojeho poskićowarja.",
        "da": "Brug DAV-adressen fra din udbyder.", "nb": "Bruk DAV-adressen fra leverandøren din.",
        "hi": "अपने सेवा प्रदाता द्वारा दिया गया DAV पता उपयोग करें।",
        "zh_CN": "请使用服务商提供的 DAV 地址。", "ja": "サービス提供元の DAV アドレスを使用してください。",
        "ar": "استخدم عنوان DAV الذي يقدمه مزود الخدمة.",
        "uk": "Використовуйте адресу DAV, надану вашим постачальником.",
        "be": "Выкарыстоўвайце адрас DAV, прадастаўлены вашым пастаўшчыком.",
        "tr": "Hizmet sağlayıcınızın verdiği DAV adresini kullanın.",
    },
    "Only HTTPS. The password is stored securely on this computer.": {
        "de": "Nur HTTPS. Das Kennwort wird geschützt auf diesem Rechner gespeichert.",
        "fr": "HTTPS uniquement. Le mot de passe est conservé de manière sécurisée sur cet ordinateur.",
        "es": "Solo HTTPS. La contraseña se guarda de forma segura en este equipo.",
        "it": "Solo HTTPS. La password viene memorizzata in modo sicuro su questo computer.",
        "nl": "Alleen HTTPS. Het wachtwoord wordt veilig op deze computer opgeslagen.",
        "pt": "Apenas HTTPS. A palavra-passe é guardada de forma segura neste computador.",
        "ru": "Только HTTPS. Пароль надёжно хранится на этом компьютере.",
        "cs": "Pouze HTTPS. Heslo se bezpečně ukládá na tomto počítači.",
        "pl": "Tylko HTTPS. Hasło jest bezpiecznie przechowywane na tym komputerze.",
        "hsb": "Jenož HTTPS. Hesło so škitane na tutym ličaku składuje.",
        "da": "Kun HTTPS. Adgangskoden gemmes sikkert på denne computer.",
        "nb": "Kun HTTPS. Passordet lagres sikkert på denne datamaskinen.",
        "hi": "केवल HTTPS। पासवर्ड इस कंप्यूटर पर सुरक्षित रूप से सहेजा जाता है।",
        "zh_CN": "仅限 HTTPS。密码将安全地存储在此计算机上。",
        "ja": "HTTPS のみ。パスワードはこのコンピューターに安全に保存されます。",
        "ar": "HTTPS فقط. تُحفظ كلمة المرور بأمان على هذا الحاسوب.",
        "uk": "Лише HTTPS. Пароль захищено зберігається на цьому комп’ютері.",
        "be": "Толькі HTTPS. Пароль бяспечна захоўваецца на гэтым камп’ютары.",
        "tr": "Yalnızca HTTPS. Parola bu bilgisayarda güvenli bir şekilde saklanır.",
    },
    "Requires a Nextcloud account.": {
        "de": "Benötigt ein Nextcloud-Konto.", "fr": "Nécessite un compte Nextcloud.",
        "es": "Requiere una cuenta de Nextcloud.", "it": "Richiede un account Nextcloud.",
        "nl": "Vereist een Nextcloud-account.", "pt": "Requer uma conta Nextcloud.",
        "ru": "Требуется учётная запись Nextcloud.", "cs": "Vyžaduje účet Nextcloud.",
        "pl": "Wymaga konta Nextcloud.", "hsb": "Trjeba Nextcloud-konto.",
        "da": "Kræver en Nextcloud-konto.", "nb": "Krever en Nextcloud-konto.",
        "hi": "Nextcloud खाता आवश्यक है।", "zh_CN": "需要 Nextcloud 账户。",
        "ja": "Nextcloud アカウントが必要です。", "ar": "يتطلب حساب Nextcloud.",
        "uk": "Потрібен обліковий запис Nextcloud.", "be": "Патрабуецца ўліковы запіс Nextcloud.",
        "tr": "Nextcloud hesabı gerektirir.",
    },
    "This calendar does not support tasks (VTODO).": {
        "de": "Dieser Kalender unterstützt keine Aufgaben (VTODO).",
        "fr": "Ce calendrier ne prend pas en charge les tâches (VTODO).",
        "es": "Este calendario no admite tareas (VTODO).",
        "it": "Questo calendario non supporta le attività (VTODO).",
        "nl": "Deze agenda ondersteunt geen taken (VTODO).",
        "pt": "Este calendário não suporta tarefas (VTODO).",
        "ru": "Этот календарь не поддерживает задачи (VTODO).",
        "cs": "Tento kalendář nepodporuje úkoly (VTODO).",
        "pl": "Ten kalendarz nie obsługuje zadań (VTODO).",
        "hsb": "Tutón protyka nadawki (VTODO) njepodpěruje.",
        "da": "Denne kalender understøtter ikke opgaver (VTODO).",
        "nb": "Denne kalenderen støtter ikke oppgaver (VTODO).",
        "hi": "यह कैलेंडर कार्यों (VTODO) का समर्थन नहीं करता।",
        "zh_CN": "此日历不支持任务（VTODO）。", "ja": "このカレンダーはタスク（VTODO）に対応していません。",
        "ar": "هذا التقويم لا يدعم المهام (VTODO).",
        "uk": "Цей календар не підтримує завдання (VTODO).",
        "be": "Гэты каляндар не падтрымлівае задачы (VTODO).",
        "tr": "Bu takvim görevleri (VTODO) desteklemiyor.",
    },
    "Google requires browser sign-in. Google synchronization is not yet available in this Windows version; a DAV password cannot enable it.": {
        "de": "Google benötigt eine Anmeldung im Browser. Der Google-Abgleich ist in dieser Windows-Version noch nicht verfügbar; ein DAV-Kennwort kann ihn nicht aktivieren.",
        "fr": "Google exige une connexion dans le navigateur. La synchronisation Google n’est pas encore disponible dans cette version Windows ; un mot de passe DAV ne peut pas l’activer.",
        "es": "Google requiere iniciar sesión en el navegador. La sincronización con Google aún no está disponible en esta versión de Windows; una contraseña DAV no puede activarla.",
        "it": "Google richiede l’accesso nel browser. La sincronizzazione Google non è ancora disponibile in questa versione Windows; una password DAV non può attivarla.",
        "nl": "Google vereist aanmelding in de browser. Google-synchronisatie is nog niet beschikbaar in deze Windows-versie; een DAV-wachtwoord kan deze niet inschakelen.",
        "pt": "O Google requer início de sessão no navegador. A sincronização com o Google ainda não está disponível nesta versão Windows; uma palavra-passe DAV não a pode ativar.",
        "ru": "Google требует входа через браузер. Синхронизация с Google пока недоступна в этой версии для Windows; пароль DAV не может её включить.",
        "cs": "Google vyžaduje přihlášení v prohlížeči. Synchronizace s Googlem v této verzi pro Windows zatím není dostupná; heslo DAV ji nemůže zapnout.",
        "pl": "Google wymaga logowania w przeglądarce. Synchronizacja z Google nie jest jeszcze dostępna w tej wersji dla Windows; hasło DAV nie może jej włączyć.",
        "hsb": "Google sej přizjewjenje we wobhladowaku žada. Synchronizacija z Google w tutej Windows-wersiji hišće k dispoziciji njeje; hesło DAV ju njemóže zmóžnić.",
        "da": "Google kræver login i browseren. Google-synkronisering er endnu ikke tilgængelig i denne Windows-version; en DAV-adgangskode kan ikke aktivere den.",
        "nb": "Google krever innlogging i nettleseren. Google-synkronisering er ennå ikke tilgjengelig i denne Windows-versjonen; et DAV-passord kan ikke aktivere den.",
        "hi": "Google के लिए ब्राउज़र में साइन इन करना आवश्यक है। इस Windows संस्करण में Google सिंक्रनाइज़ेशन अभी उपलब्ध नहीं है; DAV पासवर्ड इसे सक्षम नहीं कर सकता।",
        "zh_CN": "Google 需要在浏览器中登录。此 Windows 版本尚不支持 Google 同步；DAV 密码无法启用此功能。",
        "ja": "Google にはブラウザーでのログインが必要です。この Windows 版では Google 同期はまだ利用できません。DAV パスワードでは有効にできません。",
        "ar": "يتطلب Google تسجيل الدخول في المتصفح. مزامنة Google غير متاحة بعد في إصدار Windows هذا؛ لا يمكن تفعيلها بكلمة مرور DAV.",
        "uk": "Google потребує входу через браузер. Синхронізація з Google поки недоступна в цій версії для Windows; пароль DAV не може її ввімкнути.",
        "be": "Google патрабуе ўваходу праз браўзер. Сінхранізацыя з Google пакуль недаступная ў гэтай версіі для Windows; пароль DAV не можа яе ўключыць.",
        "tr": "Google, tarayıcıda oturum açılmasını gerektirir. Bu Windows sürümünde Google eşitlemesi henüz kullanılamıyor; DAV parolası bunu etkinleştiremez.",
    },
    "Sign-in failed. Check the account and authentication method required by your provider.": {
        "de": "Anmeldung fehlgeschlagen. Prüfen Sie das Konto und das vom Anbieter verlangte Anmeldeverfahren.",
        "fr": "Échec de la connexion. Vérifiez le compte et la méthode d’authentification exigée par votre fournisseur.",
        "es": "No se pudo iniciar sesión. Compruebe la cuenta y el método de autenticación requerido por su proveedor.",
        "it": "Accesso non riuscito. Controllare l’account e il metodo di autenticazione richiesto dal fornitore.",
        "nl": "Aanmelden mislukt. Controleer het account en de vereiste aanmeldmethode van uw aanbieder.",
        "pt": "Falha ao iniciar sessão. Verifique a conta e o método de autenticação exigido pelo fornecedor.",
        "ru": "Не удалось войти. Проверьте учётную запись и требуемый поставщиком способ аутентификации.",
        "cs": "Přihlášení se nezdařilo. Zkontrolujte účet a způsob ověření požadovaný poskytovatelem.",
        "pl": "Logowanie nie powiodło się. Sprawdź konto i metodę uwierzytelniania wymaganą przez dostawcę.",
        "hsb": "Přizjewjenje je so njeporadźiło. Přepruwujće konto a wot poskićowarja požadane přizjewjenske jednanje.",
        "da": "Login mislykkedes. Kontrollér kontoen og den godkendelsesmetode, som din udbyder kræver.",
        "nb": "Innlogging mislyktes. Kontroller kontoen og autentiseringsmetoden leverandøren krever.",
        "hi": "साइन इन विफल रहा। खाते और प्रदाता द्वारा आवश्यक प्रमाणीकरण विधि की जाँच करें।",
        "zh_CN": "登录失败。请检查账户及提供商要求的身份验证方式。",
        "ja": "ログインに失敗しました。アカウントとプロバイダーが要求する認証方法を確認してください。",
        "ar": "فشل تسجيل الدخول. تحقق من الحساب وطريقة المصادقة التي يتطلبها مزود الخدمة.",
        "uk": "Не вдалося ввійти. Перевірте обліковий запис і спосіб автентифікації, якого вимагає постачальник.",
        "be": "Не ўдалося ўвайсці. Праверце ўліковы запіс і спосаб аўтэнтыфікацыі, які патрабуе пастаўшчык.",
        "tr": "Oturum açılamadı. Hesabı ve sağlayıcınızın gerektirdiği kimlik doğrulama yöntemini kontrol edin.",
    },
    "The server denied access. Check this account's permissions.": {
        "de": "Der Server hat den Zugriff verweigert. Prüfen Sie die Berechtigungen dieses Kontos.",
        "fr": "Le serveur a refusé l’accès. Vérifiez les autorisations de ce compte.",
        "es": "El servidor denegó el acceso. Compruebe los permisos de esta cuenta.",
        "it": "Il server ha negato l’accesso. Controllare i permessi di questo account.",
        "nl": "De server heeft toegang geweigerd. Controleer de machtigingen van dit account.",
        "pt": "O servidor recusou o acesso. Verifique as permissões desta conta.",
        "ru": "Сервер отказал в доступе. Проверьте разрешения этой учётной записи.",
        "cs": "Server odepřel přístup. Zkontrolujte oprávnění tohoto účtu.",
        "pl": "Serwer odmówił dostępu. Sprawdź uprawnienia tego konta.",
        "hsb": "Serwer je přistup wotpokazał. Přepruwujće prawa tutoho konta.",
        "da": "Serveren nægtede adgang. Kontrollér denne kontos tilladelser.",
        "nb": "Serveren nektet tilgang. Kontroller tillatelsene til denne kontoen.",
        "hi": "सर्वर ने पहुँच अस्वीकार कर दी। इस खाते की अनुमतियाँ जाँचें।",
        "zh_CN": "服务器拒绝访问。请检查此账户的权限。",
        "ja": "サーバーがアクセスを拒否しました。このアカウントの権限を確認してください。",
        "ar": "رفض الخادم الوصول. تحقق من أذونات هذا الحساب.",
        "uk": "Сервер відмовив у доступі. Перевірте дозволи цього облікового запису.",
        "be": "Сервер адмовіў у доступе. Праверце дазволы гэтага ўліковага запісу.",
        "tr": "Sunucu erişimi reddetti. Bu hesabın izinlerini kontrol edin.",
    },
    "Are you really sure?": {
        "ar": "هل أنت متأكد حقًا؟", "be": "Вы сапраўды ўпэўнены?",
        "cs": "Opravdu jste si jisti?", "da": "Er du helt sikker?",
        "de": "Sind Sie wirklich sicher?", "es": "¿Está realmente seguro?",
        "fr": "Êtes-vous vraiment sûr ?", "hi": "क्या आप वाकई सुनिश्चित हैं?",
        "hsb": "Sće woprawdźe wěsty?", "it": "È davvero sicuro?",
        "ja": "本当によろしいですか？", "nb": "Er du helt sikker?",
        "nl": "Weet u het echt zeker?", "pl": "Czy na pewno?",
        "pt": "Tem mesmo a certeza?", "ru": "Вы действительно уверены?",
        "tr": "Gerçekten emin misiniz?", "uk": "Ви справді впевнені?",
        "zh_CN": "您真的确定吗？",
    },
    "Deleted and missing data is restored; newer existing data is retained.": {
        "fr": "Les données supprimées et manquantes sont restaurées ; les données existantes plus récentes sont conservées.",
        "es": "Se restauran los datos eliminados y faltantes; se conservan los datos existentes más recientes.",
        "it": "I dati eliminati e mancanti vengono ripristinati; i dati esistenti più recenti vengono conservati.",
        "nl": "Verwijderde en ontbrekende gegevens worden hersteld; nieuwere bestaande gegevens blijven behouden.",
        "pt": "Os dados eliminados e em falta são restaurados; os dados existentes mais recentes são mantidos.",
        "ru": "Удалённые и отсутствующие данные восстанавливаются; более новые существующие данные сохраняются.",
        "cs": "Odstraněná a chybějící data se obnoví; novější existující data zůstanou zachována.",
        "pl": "Usunięte i brakujące dane zostaną przywrócone; nowsze istniejące dane zostaną zachowane.",
        "hsb": "Zhašane a falowace daty so wobnowja; nowše eksistowace daty so wobchowaja.",
        "da": "Slettede og manglende data gendannes; nyere eksisterende data bevares.",
        "nb": "Slettede og manglende data gjenopprettes; nyere eksisterende data beholdes.",
        "hi": "हटाया गया और अनुपलब्ध डेटा पुनर्स्थापित किया जाता है; नया मौजूदा डेटा रखा जाता है।",
        "zh_CN": "恢复已删除和缺失的数据；保留较新的现有数据。",
        "ja": "削除されたデータと不足しているデータを復元し、既存の新しいデータは保持します。",
        "ar": "تُستعاد البيانات المحذوفة والمفقودة، وتُحتفظ بالبيانات الموجودة الأحدث.",
        "uk": "Видалені та відсутні дані відновлюються; новіші наявні дані зберігаються.",
        "be": "Выдаленыя і адсутныя даныя аднаўляюцца; навейшыя існыя даныя захоўваюцца.",
        "tr": "Silinen ve eksik veriler geri yüklenir; daha yeni mevcut veriler korunur.",
    },
    "The selected areas are reset exactly; data added later is removed.": {
        "fr": "Les zones sélectionnées sont réinitialisées exactement ; les données ajoutées ultérieurement sont supprimées.",
        "es": "Las áreas seleccionadas se restablecen exactamente; se eliminan los datos añadidos posteriormente.",
        "it": "Le aree selezionate vengono ripristinate esattamente; i dati aggiunti in seguito vengono rimossi.",
        "nl": "De geselecteerde gebieden worden exact teruggezet; later toegevoegde gegevens worden verwijderd.",
        "pt": "As áreas selecionadas são repostas exatamente; os dados adicionados posteriormente são removidos.",
        "ru": "Выбранные области точно возвращаются к прежнему состоянию; добавленные позже данные удаляются.",
        "cs": "Vybrané oblasti se přesně vrátí do dřívějšího stavu; později přidaná data se odstraní.",
        "pl": "Wybrane obszary zostaną dokładnie przywrócone; dane dodane później zostaną usunięte.",
        "hsb": "Wubrane wobłuki so eksaktnje wróćo stajeja; pozdźišo přidate daty so wotstronja.",
        "da": "De valgte områder nulstilles nøjagtigt; data, der er tilføjet senere, fjernes.",
        "nb": "De valgte områdene tilbakestilles nøyaktig; data som ble lagt til senere, fjernes.",
        "hi": "चुने गए क्षेत्रों को ठीक पुराने रूप में लौटाया जाता है; बाद में जोड़ा गया डेटा हटा दिया जाता है।",
        "zh_CN": "所选区域将精确重置；之后添加的数据将被移除。",
        "ja": "選択した領域を以前の状態に正確に戻し、その後に追加されたデータを削除します。",
        "ar": "تُعاد المناطق المحددة بدقة إلى حالتها السابقة، وتُحذف البيانات المضافة لاحقًا.",
        "uk": "Вибрані області точно повертаються до попереднього стану; додані пізніше дані видаляються.",
        "be": "Выбраныя вобласці дакладна вяртаюцца да ранейшага стану; дададзеныя пазней даныя выдаляюцца.",
        "tr": "Seçilen alanlar önceki duruma tam olarak döndürülür; daha sonra eklenen veriler kaldırılır.",
    },
    "Operating system": {
        "ar": "نظام التشغيل", "be": "Аперацыйная сістэма", "cs": "Operační systém",
        "da": "Operativsystem", "de": "Betriebssystem", "es": "Sistema operativo",
        "fr": "Système d’exploitation", "hi": "ऑपरेटिंग सिस्टम", "hsb": "Dźěłowy system",
        "it": "Sistema operativo", "ja": "オペレーティングシステム", "nb": "Operativsystem",
        "nl": "Besturingssysteem", "pl": "System operacyjny", "pt": "Sistema operativo",
        "ru": "Операционная система", "tr": "İşletim sistemi", "uk": "Операційна система",
        "zh_CN": "操作系统",
    },
}


def po_katalog(pfad):
    with tempfile.TemporaryDirectory(prefix="magnolie-po-merge-") as ordner:
        mo = os.path.join(ordner, "catalog.mo")
        subprocess.run([os.environ.get("MAGNOLIE_MSGFMT", "msgfmt"), "-o", mo, pfad],
                       check=True)
        with open(mo, "rb") as datei:
            return dict(gettext.GNUTranslations(datei)._catalog)


def js_katalog(pfad):
    text = open(pfad, encoding="utf-8").read()
    treffer = re.fullmatch(r'window\.MagnolieI18n\.registerCatalog\((".*?"),\s*(\{.*\})\);\s*',
                           text, re.DOTALL)
    if not treffer:
        raise ValueError("Ungültiger generierter Webkatalog: " + pfad)
    return json.loads(treffer.group(2))["messages"]


def feld(block, name):
    treffer = re.search(r"^" + name + r' (".*")$', block, re.MULTILINE)
    if not treffer:
        return None
    wert = json.loads(treffer.group(1))
    position = treffer.end()
    while position < len(block):
        folge = re.match(r'\n(".*")', block[position:])
        if not folge:
            break
        wert += json.loads(folge.group(1))
        position += len(folge.group(0))
    return wert


def quoted(name, wert):
    return name + " " + json.dumps(wert, ensure_ascii=False)


def haupt(argv):
    if len(argv) != 7:
        raise SystemExit("Aufruf: po_vereinigen.py VORLAGE.pot AKTUELL.po ALT.js ALT-NATIV.json SPRACHE ZIEL.po")
    vorlage, aktuell, alt, alt_nativ, sprache, ziel = argv[1:]
    aktuelle = po_katalog(aktuell)
    alte = js_katalog(alt)
    with open(alt_nativ, encoding="utf-8") as datei:
        alte.update(json.load(datei)["locales"][sprache])
    bloecke = open(vorlage, encoding="utf-8").read().split("\n\n")
    ausgabe = []
    for block in bloecke:
        msgid = feld(block, "msgid")
        if msgid is None:
            ausgabe.append(block)
            continue
        if msgid == "":
            kopf = aktuelle.get("", "")
            kopf_zeilen = 'msgstr ""\n' + "\n".join(
                json.dumps(zeile + "\n", ensure_ascii=False) for zeile in kopf.splitlines())
            ausgabe.append(re.sub(r'^msgstr ""(?:\n".*")*', lambda _: kopf_zeilen,
                                  block.replace("#, fuzzy\n", ""), count=1, flags=re.MULTILINE))
            continue
        context = feld(block, "msgctxt")
        key = (context + "\x04" + msgid) if context else msgid
        plural = feld(block, "msgid_plural")
        if plural is None:
            # Existing PO translations are authoritative; generated catalogs
            # and explicit additions only fill missing entries.
            wert = aktuelle.get(key) or alte.get(key) or ERGÄNZUNGEN.get(key, {}).get(sprache)
            if not isinstance(wert, str) or not wert:
                raise ValueError("Übersetzung fehlt: " + key)
            ersetzt = re.sub(r'^msgstr ""(?:\n".*")*', lambda _: quoted("msgstr", wert), block,
                             count=1, flags=re.MULTILINE)
        else:
            altwerte = alte.get(key, [])
            zeilen = []
            index = 0
            while (key, index) in aktuelle or index < len(altwerte):
                wert = aktuelle.get((key, index)) or (altwerte[index] if index < len(altwerte) else "")
                if not wert:
                    raise ValueError("Pluralübersetzung fehlt: " + key)
                zeilen.append(quoted("msgstr[%d]" % index, wert))
                index += 1
            ersetzt = re.sub(r'^msgstr\[0\] ""(?:\nmsgstr\[\d+\] "")*', lambda _: "\n".join(zeilen),
                             block, count=1, flags=re.MULTILINE)
        ausgabe.append(ersetzt)
    with open(ziel, "w", encoding="utf-8", newline="\n") as datei:
        datei.write("\n\n".join(ausgabe).rstrip() + "\n")


if __name__ == "__main__":
    haupt(sys.argv)
