.TH MAGNOLIE-HANDBUCH 1 "srpen 2026" "Příručka Magnolie 2.0.14" "Uživatelské příkazy"
.SH NÁZEV
magnolie-handbuch \- otevře uživatelskou příručku organizéru Magnolie
.SH POUŽITÍ
.B magnolie-handbuch
.RI [ volba ]
.RI [ \-\-language\  jazyk ]
.SH POPIS
.B Příručka Magnolie
otevře úplnou ilustrovanou uživatelskou příručku organizéru Magnolie. Příručku
lze procházet na obrazovce, vytisknout nebo exportovat do souboru PDF.
.PP
V rámci jednoho uživatelského sezení se otevře pouze jedno okno příručky.
Opětovné spuštění příkazu zobrazí již otevřené okno.
.SH TVARY PŘÍKAZOVÉHO ŘÁDKU
Neutrální krátké aliasy a anglické dlouhé tvary jsou:
.nf
\-h \-\-help; \-V \-\-version; \-l \-\-language; \-P \-\-pot-template.
.fi
Přijímají se německé i anglické dlouhé tvary.
.SH VOLBY
.TP
.BR \-\-language " " LANGUAGE , " " \-\-sprache " " SPRACHE
Pro toto spuštění použije němčinu (\fBde\fR), angličtinu (\fBen\fR) nebo jazyk
systému (\fBsystem\fR). Tím se zvolí jazyk výstupu příkazu před zobrazením
nápovědy a jazyk WebKitu v nově otevřeném okně. Uložená nastavení se nezmění.
.TP
.BR \-\-pot-template " [" FILE "]", " " \-\-pot " [" SOUBOR "]"
Vytvoří reprodukovatelnou šablonu gettext a skončí. Bez argumentu souboru
zapíše \fBmagnolie-handbuch.pot\fR do aktuálního adresáře; jinak ji zapíše do
zadané cesty. Při úspěchu vypíše absolutní cestu k výstupu.
.TP
.BR \-\-help , " " \-\-hilfe
Zobrazí stručný přehled příkazu.
.SH PROSTŘEDÍ
.TP
.B MAGNOLIE_HANDBUCH_WEB
Použije jiný adresář obsahující rozhraní příručky. Určeno pro vývoj a
testování.
.SH "VIZ TAKÉ"
.BR magnolie-organizer (1)
.SH AUTOR
Napsal Maik Walter.
