.TH MAGNOLIE-ORGANIZER 1 "август 2026 г." "Magnolie Organizer 2.0.18" "Пользовательские команды"
.SH ИМЯ
magnolie-organizer \- персональный органайзер в классическом бумажном стиле
.SH СИНТАКСИС
.B magnolie-organizer
.RI [ параметр ]
.RI [ \-\-language\  язык ]
.SH ОПИСАНИЕ
.B Magnolie Organizer
объединяет календарь, задачи, контакты, заметки, годовщины и годовой
планировщик. Данные хранятся локально; при желании их можно синхронизировать
через Evolution Data Server или передавать через зашифрованную службу
Magnolienbaum.
.PP
В каждом пользовательском сеансе открывается только один графический
экземпляр. Повторный запуск команды выводит на экран уже открытое окно, даже
если оно скрыто в области уведомлений.
.SH ФОРМЫ КОМАНДНОЙ СТРОКИ
Нейтральные короткие псевдонимы и английские длинные формы:
.nf
\-h \-\-help; \-V \-\-version; \-l \-\-language; \-P \-\-pot-template;
\-r \-\-reminder-check; \-w \-\-alarm-monitor; \-p \-\-reminder-test;
\-t \-\-tray-start; \-d \-\-debug; \-b \-\-background-service.
.fi
Принимаются как немецкие, так и английские длинные формы.
.SH ПАРАМЕТРЫ
.TP
.B \-\-reminder-check
Проверить наличие наступивших напоминаний. Обычно этот параметр используется
службой пользовательского сеанса.
.TP
.B \-\-alarm-monitor
Запустить монитор напоминаний в фоновом режиме.
.TP
.B \-\-tray-start
Запустить органайзер через запись автозапуска в области уведомлений.
.TP
.B \-\-reminder-test
Проверить напоминания и вывести диагностический отчёт.
.TP
.B \-\-debug
Продолжить обычную работу, записывая закрытые для посторонних ротируемые
диагностические сведения о запуске, сеансе, единственном экземпляре, окне и
области уведомлений в
\fB~/.local/state/magnolie-organizer/debug.log\fR. Перед диагностическим
запуском завершите уже работающий экземпляр; повторный вызов лишь активирует
существующий процесс.
.TP
.BR \-\-language " " LANGUAGE , " " \-\-sprache " " SPRACHE
Использовать для этого вызова немецкий (\fBde\fR), английский (\fBen\fR) или
системный язык (\fBsystem\fR). Язык выбирается для вывода команд до перехода в
режим справки, диагностики или фоновой работы, а также для интерфейса WebKit
вновь открытого графического экземпляра. Сохранённые настройки не изменяются.
.TP
.BR \-\-pot-template " [" FILE "]", " " \-\-pot " [" DATEI "]"
Создать воспроизводимый шаблон gettext и завершить работу. Если файл не
указан, записать \fBmagnolie-organizer.pot\fR в текущий каталог; в противном
случае записать его по указанному пути. При успешном выполнении выводится
абсолютный путь к выходному файлу.
.TP
.BR \-\-help , " " \-\-hilfe
Показать краткий обзор команд.
.SH СЕТЬ MAGNOLIENBAUM
Если служба Magnolienbaum включена, она прослушивает TCP-порт 8737 по IPv4 и
IPv6. Локальные ветви объявляются и обнаруживаются через mDNS/DNS-SD как
\fB_magnolie._tcp.local.\fR. UDP-порт 8737 остаётся доступным как ограниченный
резервный механизм обнаружения для старых версий; mDNS использует UDP-порт
5353.
.PP
Имя узла, IPv4- или IPv6-адрес также можно ввести вручную. Файлы сопряжения
принимают доступные литералы IPv4 и IPv6. Квадратные скобки IPv6, необходимые
в URL, добавляются автоматически и не должны храниться в файлах сопряжения.
.SH КОНФИДЕНЦИАЛЬНОСТЬ ПРОГНОЗА ПОГОДЫ
Необязательный прогноз отправляет запросы на \fBwttr.in\fR. Сначала
используется населённый пункт из адреса пользователя, затем локально
считываются пользовательские данные LibreOffice. Если населённый пункт не
указан ни там, ни там, wttr.in может определить его приблизительно по
публичному IP-адресу, видимому службе. Параметр календаря
\(lqНе получать погоду без местоположения\(rq предотвращает любые сетевые
запросы погоды в этом случае.
.SH ФАЙЛЫ
.TP
.I ~/.local/share/magnolie-organizer/
Пользовательские данные, настройки, резервные копии и состояние напоминаний.
.TP
.I ~/.config/autostart/magnolie-organizer-tray.desktop
Необязательная запись автозапуска в области уведомлений.
.TP
.I ~/.local/state/magnolie-organizer/debug.log
Доступный только владельцу журнал диагностики, создаваемый при использовании
\fB\-\-debug\fR.
.SH ПЕРЕМЕННЫЕ ОКРУЖЕНИЯ
.TP
.B MAGNOLIE_ORGANIZER_WEB
Использовать другой каталог с веб-интерфейсом. Предназначено для разработки и
тестирования.
.SH СМ. ТАКЖЕ
.BR magnolie-handbuch (1)
.SH АВТОР
Автор: Maik Walter.
