.TH MAGNOLIE-HANDBUCH 1 "awgust 2026" "Přiručka Magnolie 2.0.1" "Wužiwarske přikazy"
.SH MJENO
magnolie-handbuch \- wužiwarsku přiručku organizatora Magnolie wočinić
.SH SYNOPSA
.B magnolie-handbuch
.RI [ opcija ]
.RI [ \-\-sprache\  rěč ]
.SH WOPISANJE
.B Přiručka Magnolie
wočinja dospołnu wobrazowu wužiwarsku přiručku za organizator Magnolie.
Přiručku móžeće na wobrazowce čitać, ćišćeć abo jako PDF-dataju eksportować.
.PP
Za kóžde wužiwarske posedźenje so jenož jedne wokno přiručki wočinja.
Znowowuwjedźenje přikaza hižo eksistowace wokno pokazuje.
.SH OPCIJE
.TP
.BR \-\-sprache " " SPRACHE , " " \-\-language " " LANGUAGE
Za tute wužiće němčinu (\fBde\fR), jendźelšćinu (\fBen\fR) abo systemowu rěč
(\fBsystem\fR) wužiwać. To wuběra rěč přikazoweho wudaća před pomocu a rěč
WebKit nowo wočinjenego wokna. Składowane nastajenja so njezměnja.
.TP
.BR \-\-pot " [" DATAJA "]", " " \-\-pot-template " [" FILE "]"
Reprodukowatelnu předłohu gettext wutworić a program skónčić. Bjez datajoweho
argumenta so \fBmagnolie-handbuch.pot\fR do aktualneho zapisa zapisuje; hewak
so do podateje šćežki zapisuje. Po wuspěchu so absolutna wudawanska šćežka
wuda.
.TP
.BR \-\-hilfe , " " \-\-help
Krótki přehlad přikaza pokazać.
.SH WOKOLINA
.TP
.B MAGNOLIE_HANDBUCH_WEB
Alternatiwny zapis z powjerchom přiručki wužiwać. Za wuwiwanje a testowanje
myslene.
.SH "HLEJ TEŽ"
.BR magnolie-organizer (1)
.SH AWTOR
Spisał Maik Walter.
