.TH MAGNOLIE-ORGANIZER 1 "Augustus 2026" "Magnolie Organizer 2.0.14" "Gebruikersopdrachten"
.SH NAAM
magnolie-organizer \- persoonlijke organizer in klassiek papieren ontwerp
.SH SYNOPSIS
.B magnolie-organizer
.RI [ optie ]
.RI [ \-\-language\  taal ]
.SH BESCHRIJVING
.B Magnolie Organizer
combineert een agenda, taken, contactpersonen, notities, gedenkdagen en een
jaarplanner. Gegevens worden lokaal opgeslagen en kunnen desgewenst via
Evolution Data Server worden gesynchroniseerd of via de versleutelde dienst
Magnolienbaum worden gedeeld.
.PP
Per gebruikerssessie wordt slechts één grafische instantie geopend. Als de
opdracht opnieuw wordt gestart, verschijnt het bestaande venster, ook wanneer
dit in het systeemvak verborgen is.
.SH OPDRACHTREGELVORMEN
De neutrale korte aliassen en Engelse lange vormen zijn:
.nf
\-h \-\-help; \-V \-\-version; \-l \-\-language; \-P \-\-pot-template;
\-r \-\-reminder-check; \-w \-\-alarm-monitor; \-p \-\-reminder-test;
\-t \-\-tray-start; \-d \-\-debug; \-b \-\-background-service.
.fi
Zowel Duitse als Engelse lange vormen worden geaccepteerd.
.SH OPTIES
.TP
.B \-\-reminder-check
Controleer op vervallen herinneringen. Deze optie wordt gewoonlijk door de
sessiedienst gebruikt.
.TP
.B \-\-alarm-monitor
Voer de herinneringsmonitor op de achtergrond uit.
.TP
.B \-\-tray-start
Start de organizer via het item voor automatisch starten in het systeemvak.
.TP
.B \-\-reminder-test
Test herinneringen en druk een diagnoserapport af.
.TP
.B \-\-debug
Ga door met de normale werking en schrijf daarbij persoonlijke, roterende
diagnostiek over opstarten, sessie, enkelvoudige instantie, venster en
systeemvak naar \fB~/.local/state/magnolie-organizer/debug.log\fR. Sluit een
reeds actieve instantie af voordat een diagnostische uitvoering wordt gestart;
een tweede aanroep activeert alleen het bestaande proces.
.TP
.BR \-\-language " " LANGUAGE , " " \-\-sprache " " SPRACHE
Gebruik Duits (\fBde\fR), Engels (\fBen\fR) of de systeemtaal (\fBsystem\fR)
voor deze aanroep. Hiermee wordt de taal gekozen voor opdrachtuitvoer vóór de
hulp-, diagnose- en achtergrondmodi en voor de WebKit-interface van een nieuw
geopende grafische instantie. Opgeslagen instellingen worden niet gewijzigd.
.TP
.BR \-\-pot-template " [" FILE "]", " " \-\-pot " [" DATEI "]"
Genereer een reproduceerbare gettext-sjabloon en sluit af. Schrijf zonder
bestandsargument \fBmagnolie-organizer.pot\fR in de huidige map; schrijf anders
naar het opgegeven pad. Bij succes wordt het absolute uitvoerpad weergegeven.
.TP
.BR \-\-help , " " \-\-hilfe
Toon een kort opdrachtoverzicht.
.SH MAGNOLIENBAUM-NETWERK
Wanneer Magnolienbaum is ingeschakeld, luistert het via IPv4 en IPv6 op
TCP-poort 8737. Lokale takken worden via mDNS/DNS-SD als
\fB_magnolie._tcp.local.\fR aangekondigd en gevonden. UDP-poort 8737 blijft
beschikbaar als beperkte terugvalmethode voor detectie door oudere versies;
mDNS gebruikt UDP-poort 5353.
.PP
Een hostnaam, IPv4-adres of IPv6-adres kan ook handmatig worden ingevoerd.
Koppelingsbestanden accepteren bereikbare letterlijke IPv4- en IPv6-adressen.
De IPv6-haken die URL's vereisen, worden automatisch toegevoegd en mogen niet
in koppelingsbestanden worden opgeslagen.
.SH WEERPRIVACY
De optionele weersverwachting verstuurt verzoeken naar \fBwttr.in\fR. Eerst
wordt de locatie in het adres van de gebruiker gebruikt, daarna lokaal gelezen
LibreOffice-gebruikersgegevens. Als geen van beide een locatie bevat, kan
wttr.in deze schatten aan de hand van het openbare IP-adres dat voor de dienst
zichtbaar is. De agendaoptie ‘Geen weer ophalen zonder locatie’ voorkomt in dat
geval alle netwerkverzoeken voor het weer.
.SH BESTANDEN
.TP
.I ~/.local/share/magnolie-organizer/
Gebruikersgegevens, instellingen, reservekopieën en herinneringsstatus.
.TP
.I ~/.config/autostart/magnolie-organizer-tray.desktop
Optioneel item voor automatisch starten in het systeemvak.
.TP
.I ~/.local/state/magnolie-organizer/debug.log
Diagnostisch logboek dat alleen toegankelijk is voor de eigenaar en wordt
aangemaakt wanneer \fB\-\-debug\fR wordt gebruikt.
.SH OMGEVING
.TP
.B MAGNOLIE_ORGANIZER_WEB
Gebruik een andere map met de webinterface. Bedoeld voor ontwikkeling en tests.
.SH ZIE OOK
.BR magnolie-handbuch (1)
.SH AUTEUR
Geschreven door Maik Walter.
