#!/usr/bin/env python3
"""Inventory static current frontend/Windows contract commands; presence is not parity."""
import argparse
import re
from project_ui import BETA, REPO, LINUX, inputs, commands, digest

SCOPES = {
    "bereit": "source: load/new/locked document; native startup untested",
    "entsperren": "partial: v1/v2 Apple crypto source; no macOS crypto run",
    "speichern": "source: durable document commit; destructive save requires checkpoint",
    "kennwort_setzen": "partial: enable for current profile only; no change/rekey",
    "beenden": "source: AppKit quit handshake; native lifecycle untested",
    "beenden_bereit": "source: correlated pending quit only",
    "beenden_abgebrochen": "source: cancel pending quit",
    "ablage_kopieren": "source: text clipboard; native pasteboard untested",
    "ablage_holen": "source: text clipboard; native pasteboard untested",
    "sicherung": "partial: encrypted whole JSON, native picker; no Gesamtarchiv",
    "sicherung_waehlen": "source: native JSON picker pins selected path/bytes",
    "sicherung_wiederherstellen": "partial: full JSON replacement + checkpoint + UI preflight; no additive/section restore",
    "mutations_snapshot": "partial: durable exact file checkpoint; no desktop journal index/retention",
    "regional_einstellungen": "source: validated durable preferences; native locale handling untested",
    "export": "partial: simple appointment ICS only",
    "erinnerung_zeigen": "partial: open/unlocked/consented session only; delivery untested",
    "erinnerung_einrichten": "LIMITATION RESPONSE ONLY: no native scheduler is configured",
    "notiz_anhang_datei": "partial: selected data-URL attachment Save only; no Open"
}


def report(snapshot):
    frontend_path = str(LINUX.relative_to(REPO)) + "/web/anwendung.js"
    windows_path = "magnolie-organizer-windows/BridgeDispatcherContract.cs"
    frontend = set(re.findall(r'\bcmd\s*:\s*["\']([a-z][a-z0-9_]+)["\']', snapshot[frontend_path].decode()))
    windows = set(re.findall(r'\["([a-z][a-z0-9_]+)"\]\s*=\s*S\(', snapshot[windows_path].decode()))
    native = set(commands(snapshot))
    if native != set(SCOPES):
        raise ValueError("Update the explicit scope for every native command; do not infer full support from its name.")
    rows = ["# macOS Beta Bridge Coverage", "", "Generated by `python3 tools/bridge_coverage.py --write` from current source.",
            "This is a command inventory, **not a passed-feature count or a native validation result**.",
            "Static literal calls are compared with the Windows typed contract. Computed command names",
            "and native-only menu actions need the separate feature matrix; absence here is not support.", "",
            f"Frontend SHA-256: `{digest(snapshot[frontend_path])}`", f"Windows contract SHA-256: `{digest(snapshot[windows_path])}`", "",
            "| Command | Shared frontend literal | Windows contract | macOS Beta scope |",
            "| --- | --- | --- | --- |"]
    for name in sorted(frontend | windows | native):
        rows.append(f"| `{name}` | {'yes' if name in frontend else '—'} | {'yes' if name in windows else '—'} | {SCOPES.get(name, 'UNSUPPORTED: negative Beta response')} |")
    return "\n".join(rows) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    text = report(inputs())
    if args.write:
        (BETA / "BRIDGE-COVERAGE.md").write_text(text)
        print("Wrote macOS Beta static command inventory; no parity or native pass claim.")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
