.TH MAGNOLIE-HANDBUCH 1 "sierpień 2026" "Podręcznik Magnolie 2.0.4" "Polecenia użytkownika"
.SH NAZWA
magnolie-handbuch \- otwiera podręcznik użytkownika organizera Magnolie
.SH SKŁADNIA
.B magnolie-handbuch
.RI [ opcja ]
.RI [ \-\-sprache\  język ]
.SH OPIS
.B Podręcznik Magnolie
otwiera kompletny, ilustrowany podręcznik użytkownika organizera Magnolie.
Podręcznik można przeglądać na ekranie, drukować lub eksportować do pliku PDF.
.PP
W ramach jednej sesji użytkownika otwierane jest tylko jedno okno podręcznika.
Ponowne uruchomienie polecenia wyświetla istniejące okno.
.SH OPCJE
.TP
.BR \-\-sprache " " SPRACHE , " " \-\-language " " LANGUAGE
Używa dla tego wywołania języka niemieckiego (\fBde\fR), angielskiego
(\fBen\fR) albo języka systemowego (\fBsystem\fR). Określa to język komunikatów
polecenia przed wyświetleniem pomocy oraz język WebKit nowo otwartego okna.
Zapisane ustawienia nie są zmieniane.
.TP
.BR \-\-pot " [" PLIK "]", " " \-\-pot-template " [" FILE "]"
Tworzy powtarzalny szablon gettext i kończy działanie. Bez argumentu pliku
zapisuje \fBmagnolie-handbuch.pot\fR w bieżącym katalogu; w przeciwnym razie
zapisuje go pod wskazaną ścieżką. Po powodzeniu wypisywana jest bezwzględna
ścieżka pliku wyjściowego.
.TP
.BR \-\-hilfe , " " \-\-help
Wyświetla krótki przegląd polecenia.
.SH ŚRODOWISKO
.TP
.B MAGNOLIE_HANDBUCH_WEB
Używa alternatywnego katalogu zawierającego interfejs podręcznika. Przeznaczone
do programowania i testowania.
.SH "ZOBACZ TAKŻE"
.BR magnolie-organizer (1)
.SH AUTOR
Autor: Maik Walter.
