.TH MAGNOLIE-ORGANIZER 1 "жнівень 2026 г." "Magnolie Organizer 2.0.6" "Каманды карыстальніка"
.SH НАЗВА
magnolie-organizer \- персанальны арганайзер у класічным папяровым стылі
.SH СІНОПСІС
.B magnolie-organizer
.RI [ параметр ]
.RI [ \-\-sprache\  мова ]
.SH АПІСАННЕ
.B Magnolie Organizer
аб'ядноўвае каляндар, заданні, кантакты, нататкі, гадавіны і гадавы
планіроўшчык. Даныя захоўваюцца лакальна; пры жаданні іх можна сінхранізаваць
праз Evolution Data Server або абагульваць праз зашыфраваны сэрвіс
Magnolienbaum.
.PP
У кожным сеансе карыстальніка адкрываецца толькі адзін графічны экзэмпляр.
Паўторны запуск каманды паказвае наяўнае акно, нават калі яно схавана ў вобласці
апавяшчэнняў.
.SH ПАРАМЕТРЫ
.TP
.B \-\-erinnerung
Праверыць актуальныя напаміны. Гэты параметр звычайна выкарыстоўваецца сэрвісам
сеанса.
.TP
.B \-\-wecker
Запусціць манітор напамінаў у фонавым рэжыме.
.TP
.B \-\-tray-start
Запусціць арганайзер праз яго запіс аўтазапуску ў вобласці апавяшчэнняў.
.TP
.B \-\-probe
Праверыць напаміны і вывесці дыягнастычную справаздачу.
.TP
.B \-\-debug
Працягнуць звычайную працу, запісваючы прыватныя ратыраваныя дыягнастычныя
звесткі пра запуск, сеанс, адзіны экзэмпляр, акно і вобласць апавяшчэнняў у
\fB~/.local/state/magnolie-organizer/debug.log\fR. Перад дыягнастычным запускам
завяршыце ўжо запушчаны экзэмпляр; паўторны выклік толькі актывуе наяўны працэс.
.TP
.BR \-\-sprache " " SPRACHE , " " \-\-language " " LANGUAGE
Выкарыстоўваць для гэтага выкліку нямецкую (\fBde\fR), англійскую (\fBen\fR)
або сістэмную мову (\fBsystem\fR). Мова выбіраецца для вываду каманды да
пераходу ў рэжым даведкі, дыягностыкі ці фонавай працы, а таксама для
інтэрфейсу WebKit новага графічнага экзэмпляра. Захаваныя налады не змяняюцца.
.TP
.BR \-\-pot " [" DATEI "]", " " \-\-pot-template " [" FILE "]"
Стварыць узнаўляльны шаблон gettext і завяршыць працу. Калі аргумент файла не
зададзены, запісаць \fBmagnolie-organizer.pot\fR у бягучы каталог; інакш
запісаць яго па зададзеным шляху. Пасля паспяховага выканання выводзіцца
абсалютны шлях да выходнага файла.
.TP
.BR \-\-hilfe , " " \-\-help
Паказаць кароткі агляд каманд.
.SH СЕТКА MAGNOLIENBAUM
Калі Magnolienbaum уключаны, сэрвіс праслухоўвае TCP-порт 8737 праз IPv4 і
IPv6. Лакальныя галіны абвяшчаюцца і знаходзяцца праз mDNS/DNS-SD як
\fB_magnolie._tcp.local.\fR. UDP-порт 8737 застаецца даступным як абмежаваны
рэзервовы механізм пошуку для старых версій; mDNS выкарыстоўвае UDP-порт 5353.
.PP
Імя вузла, IPv4-адрас або IPv6-адрас таксама можна ўвесці ўручную. Файлы
спалучэння прымаюць даступныя літаралы IPv4 і IPv6. Квадратныя дужкі IPv6,
неабходныя ў URL, дадаюцца аўтаматычна і не павінны захоўвацца ў файлах
спалучэння.
.SH КАНФІДЭНЦЫЯЛЬНАСЦЬ ЗВЕСТАК ПРА НАДВОР'Е
Неабавязковы прагноз адпраўляе запыты на \fBwttr.in\fR. Спачатку
выкарыстоўваецца населены пункт з адраса карыстальніка, затым лакальна
прачытаныя даныя карыстальніка LibreOffice. Калі населенага пункта няма ні ў
адной з гэтых крыніц, wttr.in можа прыблізна вызначыць яго па агульнадаступным
IP-адрасе, бачным сэрвісу. Параметр календара \(lqНе атрымліваць звесткі пра
надвор'е без месцазнаходжання\(rq у такім выпадку прадухіляе любыя сеткавыя
запыты звестак пра надвор'е.
.SH ФАЙЛЫ
.TP
.I ~/.local/share/magnolie-organizer/
Даныя карыстальніка, налады, рэзервовыя копіі і стан напамінаў.
.TP
.I ~/.config/autostart/magnolie-organizer-tray.desktop
Неабавязковы запіс аўтазапуску ў вобласці апавяшчэнняў.
.TP
.I ~/.local/state/magnolie-organizer/debug.log
Даступны толькі ўладальніку дыягнастычны журнал, створаны пры выкарыстанні
\fB\-\-debug\fR.
.SH АСЯРОДДЗЕ
.TP
.B MAGNOLIE_ORGANIZER_WEB
Выкарыстоўваць іншы каталог, які змяшчае вэб-інтэрфейс. Прызначана для
распрацоўкі і тэсціравання.
.SH ГЛ. ТАКСАМА
.BR magnolie-handbuch (1)
.SH АЎТАР
Аўтар: Maik Walter.
